/**
 * Turn scripts/result-codes.json into src/codes.generated.ts.
 *
 *   npx tsx packages/stellar/scripts/build-codes.ts
 *
 * Same shape as packages/solana/scripts/build-errmap.ts: the harvest is the
 * evidence, this is the mechanical transform, and nothing in the generated file
 * is typed by a person. src/codes.ts holds the ENGLISH, which is ours.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

interface Harvest {
  enums: Record<string, { name: string; values: Record<string, string> }>
  operationTypes: Record<string, string>
  resultEnumForOperation: Record<string, string>
  /**
   * Byte length of each operation's SUCCESS payload, -1 when it is variable
   * and the walk has to stop. The harvester has always written this and the
   * generator has always read it; the interface simply did not declare it, so
   * the type lied about the shape of the file. Nothing broke because scripts
   * were outside the tsconfig, which is the reason this survived.
   */
  successPayloadBytes: Record<string, number>
}

const here = join(__dirname)
const h = JSON.parse(readFileSync(join(here, "result-codes.json"), "utf8")) as Harvest

const lines: string[] = [
  "// GENERATED by scripts/build-codes.ts from scripts/result-codes.json.",
  "// Do not edit. The source of truth is Stellar's own XDR at stellar/stellar-xdr.",
  "",
]

lines.push("/** OperationType discriminant to its constant name. */")
lines.push("export const OPERATION_TYPES: Record<number, string> = {")
for (const [k, v] of Object.entries(h.operationTypes).sort((a, b) => Number(a[0]) - Number(b[0]))) {
  lines.push(`  ${JSON.stringify(String(k))}: ${JSON.stringify(v)},`)
}
lines.push("}", "")

lines.push("/** Which result-code enum names an operation's outcome. Read from `union OperationResult`, never derived. */")
lines.push("export const RESULT_CODE_ENUM_FOR_OP: Record<string, string> = {")
for (const [k, v] of Object.entries(h.resultEnumForOperation).sort()) {
  lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
}
lines.push("}", "")

lines.push("/** Byte length of an operation's SUCCESS payload, -1 when variable and the walk must stop. */")
lines.push("export const SUCCESS_PAYLOAD_BYTES: Record<string, number> = {")
for (const [k, v] of Object.entries(h.successPayloadBytes).sort()) {
  lines.push(`  ${JSON.stringify(k)}: ${v},`)
}
lines.push("}", "")

lines.push("/** Every result-code enum: enum name -> signed value -> constant name. */")
lines.push("export const CODE_NAMES: Record<string, Record<number, string>> = {")
for (const [name, e] of Object.entries(h.enums).sort()) {
  lines.push(`  ${JSON.stringify(name)}: {`)
  for (const [v, c] of Object.entries(e.values).sort((a, b) => Number(b[0]) - Number(a[0]))) {
    lines.push(`    ${JSON.stringify(String(v))}: ${JSON.stringify(c)},`)
  }
  lines.push("  },")
}
lines.push("}", "")

const total = Object.values(h.enums).reduce((n, e) => n + Object.keys(e.values).length, 0)
writeFileSync(join(here, "..", "src", "codes.generated.ts"), lines.join("\n"))
process.stderr.write(`wrote ${Object.keys(h.enums).length} enums, ${total} codes, ${Object.keys(h.operationTypes).length} operation types\n`)
