/**
 * Regenerate src/errmap.ts from scripts/harvested-errors.json.
 *
 * Run harvest-errors.ts first (it accumulates across runs), then this. Keeping
 * generation separate means a bad harvest cannot silently rewrite the map, and
 * the JSON stays reviewable in a diff before anything reaches the decoder.
 */
import { readFileSync, writeFileSync } from "node:fs"

interface Harvested { program: string; code: number; name: string; message: string; seen: number }

/**
 * Slippage is the majority of what gets harvested, and it is the one family
 * where the program's own message ("ExceededSlippage") tells a user nothing
 * about what to do next. Everything else keeps the program's own words.
 */
const SLIPPAGE = /slippage|MinReturn|LessThanMinimum|TooMuchSol|MinBaseAmountOut|MinTokensOut/i
const SLIPPAGE_REASON =
  "The price moved between the quote and the transaction landing, so the trade would have returned less " +
  "than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise " +
  "your slippage tolerance slightly if it keeps happening."

function reasonFor(o: Harvested): string {
  const msg = o.message.trim().replace(/\.$/, "")
  if (SLIPPAGE.test(o.name) || SLIPPAGE.test(msg)) return SLIPPAGE_REASON
  if (msg === o.name) {
    const spaced = o.name.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    return spaced.charAt(0).toUpperCase() + spaced.slice(1) + "."
  }
  return msg + "."
}

const { named } = JSON.parse(readFileSync("scripts/harvested-errors.json", "utf8")) as { named: Harvested[] }
const byProgram = new Map<string, Harvested[]>()
for (const o of [...named].sort((a, b) => b.seen - a.seen || a.program.localeCompare(b.program))) {
  const list = byProgram.get(o.program) ?? []
  list.push(o)
  byProgram.set(o.program, list)
}

const out: string[] = []
out.push(`/** GENERATED by scripts/build-errmap.ts from scripts/harvested-errors.json. Do not edit by hand. */`)
out.push(`export interface SolanaErrorEntry { name: string; reason: string }`)
out.push(``)
out.push(`export const PROGRAM_ERRMAPS: Record<string, Record<number, SolanaErrorEntry>> = {`)
for (const [program, entries] of byProgram) {
  out.push(`  // seen ${entries.reduce((n, e) => n + e.seen, 0)}x`)
  out.push(`  "${program}": {`)
  for (const e of [...entries].sort((a, b) => a.code - b.code)) {
    out.push(`    ${e.code}: { name: ${JSON.stringify(e.name)}, reason: ${JSON.stringify(reasonFor(e))} },`)
  }
  out.push(`  },`)
}
out.push(`}`)
out.push(``)
out.push(`export const MAPPED_PROGRAMS = Object.keys(PROGRAM_ERRMAPS)`)
writeFileSync("src/errmap.ts", out.join("\n") + "\n")
console.log(`wrote src/errmap.ts: ${named.length} entries across ${byProgram.size} programs`)
