// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --local > apps/app/lib/supabase/types.ts
// Requires: Docker running + supabase start + supabase db reset

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organisations: {
        Row: {
          id: string;
          clerk_org_id: string;
          name: string;
          logo_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          clerk_org_id: string;
          name: string;
          logo_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          clerk_org_id?: string;
          name?: string;
          logo_url?: string | null;
          created_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          publishable_key: string;
          secret_key: string;
          widget_version: string;
          is_active: boolean;
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          publishable_key?: string;
          secret_key?: string;
          widget_version?: string;
          is_active?: boolean;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          publishable_key?: string;
          secret_key?: string;
          widget_version?: string;
          is_active?: boolean;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          project_id: string;
          content: string;
          embedding: number[] | null;
          metadata: Json;
          source_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          content: string;
          embedding?: number[] | null;
          metadata?: Json;
          source_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          content?: string;
          embedding?: number[] | null;
          metadata?: Json;
          source_url?: string | null;
          created_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          project_id: string;
          wallet_address: string | null;
          chain_id: string | null;
          session_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          wallet_address?: string | null;
          chain_id?: string | null;
          session_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          wallet_address?: string | null;
          chain_id?: string | null;
          session_id?: string;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: "user" | "assistant";
          content: string;
          feedback: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: "user" | "assistant";
          content: string;
          feedback?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: "user" | "assistant";
          content?: string;
          feedback?: number;
          created_at?: string;
        };
      };
      rate_limits: {
        Row: {
          id: string;
          project_id: string;
          window_start: string;
          conversation_count: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          window_start: string;
          conversation_count?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          window_start?: string;
          conversation_count?: number;
          updated_at?: string;
        };
      };
      indexing_jobs: {
        Row: {
          id: string;
          project_id: string;
          source_url: string | null;
          status: "pending" | "running" | "complete" | "failed";
          error: string | null;
          chunk_count: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          source_url?: string | null;
          status?: "pending" | "running" | "complete" | "failed";
          error?: string | null;
          chunk_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          source_url?: string | null;
          status?: "pending" | "running" | "complete" | "failed";
          error?: string | null;
          chunk_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
