// GENERATED by chain-errors.test.ts. Do not edit by hand.
//
// Every entry is the SAME string the decoder uses, read from the chain
// packages rather than retyped, so a published page cannot describe an error
// differently from the product. The test that wrote this file fails if the two
// ever disagree.
//
// Regenerate: UPDATE_CHAIN_ERRORS=1 pnpm --filter @txid/web test

export interface ChainError {
  slug: string
  /** The exact constant a wallet, explorer or SDK shows. The page H1. */
  message: string
  chain: string
  /** The operation the code belongs to, when it is operation-level. */
  scope: string | null
  /** Its signed number within its enum, which is what raw XDR carries. */
  code: number | null
  meaning: string
}

export const CHAIN_ERRORS: ChainError[] = [
  {
    "slug": "stellar-account-merge-dest-full",
    "message": "ACCOUNT_MERGE_DEST_FULL",
    "chain": "stellar",
    "scope": "ACCOUNT_MERGE",
    "code": -6,
    "meaning": "Merging would take the destination account past the maximum balance it can hold."
  },
  {
    "slug": "stellar-account-merge-has-sub-entries",
    "message": "ACCOUNT_MERGE_HAS_SUB_ENTRIES",
    "chain": "stellar",
    "scope": "ACCOUNT_MERGE",
    "code": -4,
    "meaning": "The account still has trustlines, offers, signers or data entries, and all of those have to be removed before it can be merged away."
  },
  {
    "slug": "stellar-change-trust-invalid-limit",
    "message": "CHANGE_TRUST_INVALID_LIMIT",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -3,
    "meaning": "The trustline limit given was not valid, for example lower than the balance already held."
  },
  {
    "slug": "stellar-change-trust-low-reserve",
    "message": "CHANGE_TRUST_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -4,
    "meaning": "Adding this trustline would take the account below its minimum reserve. Each trustline raises the XLM an account must keep, so more XLM is needed before it can be added."
  },
  {
    "slug": "stellar-change-trust-not-auth-maintain-liabilities",
    "message": "CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -8,
    "meaning": "The issuer has not authorised this account to maintain liabilities on the asset."
  },
  {
    "slug": "stellar-claim-claimable-balance-cannot-claim",
    "message": "CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -2,
    "meaning": "This account is not able to claim that balance right now. A claimable balance carries conditions, most often a time window, and they were not met."
  },
  {
    "slug": "stellar-claim-claimable-balance-does-not-exist",
    "message": "CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -1,
    "meaning": "There is no claimable balance with that identifier. It may already have been claimed."
  },
  {
    "slug": "stellar-claim-claimable-balance-line-full",
    "message": "CLAIM_CLAIMABLE_BALANCE_LINE_FULL",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -3,
    "meaning": "Claiming this would take the account past the limit on its trustline for the asset."
  },
  {
    "slug": "stellar-claim-claimable-balance-no-trust",
    "message": "CLAIM_CLAIMABLE_BALANCE_NO_TRUST",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -4,
    "meaning": "The account has no trustline for the asset in this claimable balance, so it cannot receive it."
  },
  {
    "slug": "stellar-create-account-underfunded",
    "message": "CREATE_ACCOUNT_UNDERFUNDED",
    "chain": "stellar",
    "scope": "CREATE_ACCOUNT",
    "code": -2,
    "meaning": "The funding account did not have enough XLM to create the new account with its minimum starting balance."
  },
  {
    "slug": "stellar-create-claimable-balance-low-reserve",
    "message": "CREATE_CLAIMABLE_BALANCE_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -2,
    "meaning": "Creating this claimable balance would take the account below its minimum reserve."
  },
  {
    "slug": "stellar-create-claimable-balance-malformed",
    "message": "CREATE_CLAIMABLE_BALANCE_MALFORMED",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -1,
    "meaning": "The claimable balance was not well formed, for example an invalid amount or claimant."
  },
  {
    "slug": "stellar-create-claimable-balance-no-trust",
    "message": "CREATE_CLAIMABLE_BALANCE_NO_TRUST",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -3,
    "meaning": "The account has no trustline for the asset it tried to lock into a claimable balance."
  },
  {
    "slug": "stellar-invoke-host-function-entry-archived",
    "message": "INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -4,
    "meaning": "The contract data this call needed has been archived. Soroban expires state that has not been used, and it has to be restored before the contract can run again."
  },
  {
    "slug": "stellar-invoke-host-function-insufficient-refundable-fee",
    "message": "INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -5,
    "meaning": "The refundable portion of the fee was not enough to cover the contract's rent and events."
  },
  {
    "slug": "stellar-invoke-host-function-resource-limit-exceeded",
    "message": "INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -3,
    "meaning": "The contract call needed more resources than the transaction reserved for it. On Soroban a transaction declares its resource budget up front, so this is a budget set too low rather than an account short of funds."
  },
  {
    "slug": "stellar-invoke-host-function-trapped",
    "message": "INVOKE_HOST_FUNCTION_TRAPPED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -2,
    "meaning": "The contract stopped partway through and rejected the call. The reason is defined by the contract rather than by Stellar, so what it means depends on the protocol. Nothing the transaction set out to do took effect."
  },
  {
    "slug": "stellar-liquidity-pool-deposit-bad-price",
    "message": "LIQUIDITY_POOL_DEPOSIT_BAD_PRICE",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_DEPOSIT",
    "code": -6,
    "meaning": "The pool's price moved outside the range this deposit allowed, so it was refused rather than filled at a worse rate."
  },
  {
    "slug": "stellar-liquidity-pool-deposit-no-trust",
    "message": "LIQUIDITY_POOL_DEPOSIT_NO_TRUST",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_DEPOSIT",
    "code": -2,
    "meaning": "The account has no trustline for the pool shares or for one of the pool's assets."
  },
  {
    "slug": "stellar-liquidity-pool-withdraw-under-minimum",
    "message": "LIQUIDITY_POOL_WITHDRAW_UNDER_MINIMUM",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_WITHDRAW",
    "code": -5,
    "meaning": "The withdrawal would have returned less than the minimum set, so it was refused. The pool's composition moved between the quote and the transaction being applied."
  },
  {
    "slug": "stellar-manage-buy-offer-buy-no-trust",
    "message": "MANAGE_BUY_OFFER_BUY_NO_TRUST",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -3,
    "meaning": "The account has no trustline for the asset it offered to buy, so it could not receive it."
  },
  {
    "slug": "stellar-manage-buy-offer-cross-self",
    "message": "MANAGE_BUY_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -8,
    "meaning": "This offer would have matched against the account's own existing offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-manage-buy-offer-line-full",
    "message": "MANAGE_BUY_OFFER_LINE_FULL",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -6,
    "meaning": "Filling this offer would take the account past the limit on its trustline for the asset it would receive."
  },
  {
    "slug": "stellar-manage-buy-offer-low-reserve",
    "message": "MANAGE_BUY_OFFER_LOW_RESERVE",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -12,
    "meaning": "Keeping this offer on the book would take the account below its minimum reserve. Each open offer raises the XLM an account must hold."
  },
  {
    "slug": "stellar-manage-buy-offer-malformed",
    "message": "MANAGE_BUY_OFFER_MALFORMED",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -1,
    "meaning": "The offer was not well formed, for example a non-positive amount or an invalid price."
  },
  {
    "slug": "stellar-manage-buy-offer-not-found",
    "message": "MANAGE_BUY_OFFER_NOT_FOUND",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -11,
    "meaning": "The offer this was trying to change or cancel is no longer on the book. It may already have been filled or cancelled."
  },
  {
    "slug": "stellar-manage-buy-offer-underfunded",
    "message": "MANAGE_BUY_OFFER_UNDERFUNDED",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -7,
    "meaning": "The account does not hold enough of the asset it offered to pay with, once the reserve is taken into account."
  },
  {
    "slug": "stellar-manage-sell-offer-buy-no-trust",
    "message": "MANAGE_SELL_OFFER_BUY_NO_TRUST",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -3,
    "meaning": "The account has no trustline for the asset it offered to buy, so it could not receive it."
  },
  {
    "slug": "stellar-manage-sell-offer-cross-self",
    "message": "MANAGE_SELL_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -8,
    "meaning": "This offer would have matched against the account's own existing offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-manage-sell-offer-line-full",
    "message": "MANAGE_SELL_OFFER_LINE_FULL",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -6,
    "meaning": "Filling this offer would take the account past the limit on its trustline for the asset it would receive."
  },
  {
    "slug": "stellar-manage-sell-offer-low-reserve",
    "message": "MANAGE_SELL_OFFER_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -12,
    "meaning": "Keeping this offer on the book would take the account below its minimum reserve. Each open offer raises the XLM an account must hold."
  },
  {
    "slug": "stellar-manage-sell-offer-malformed",
    "message": "MANAGE_SELL_OFFER_MALFORMED",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -1,
    "meaning": "The offer was not well formed, for example a non-positive amount or an invalid price."
  },
  {
    "slug": "stellar-manage-sell-offer-not-found",
    "message": "MANAGE_SELL_OFFER_NOT_FOUND",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -11,
    "meaning": "The offer this was trying to change or cancel is no longer on the book. It may already have been filled or cancelled."
  },
  {
    "slug": "stellar-manage-sell-offer-underfunded",
    "message": "MANAGE_SELL_OFFER_UNDERFUNDED",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -7,
    "meaning": "The account does not hold enough of the asset it offered to sell, once the reserve is taken into account."
  },
  {
    "slug": "stellar-op-too-many-subentries",
    "message": "opTOO_MANY_SUBENTRIES",
    "chain": "stellar",
    "scope": null,
    "code": -4,
    "meaning": "The account already holds the maximum number of subentries (trustlines, offers, signers and data entries), so another could not be added."
  },
  {
    "slug": "stellar-path-payment-strict-receive-line-full",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over. The recipient sets that limit and can raise it."
  },
  {
    "slug": "stellar-path-payment-strict-receive-malformed",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_MALFORMED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -1,
    "meaning": "The swap was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-path-payment-strict-receive-no-destination",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created before it can be paid."
  },
  {
    "slug": "stellar-path-payment-strict-receive-no-trust",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -6,
    "meaning": "The destination has no trustline for the asset being delivered. On Stellar an account has to explicitly trust an asset before it can receive it, so this is something the recipient sets up, not a problem with the payment."
  },
  {
    "slug": "stellar-path-payment-strict-receive-not-authorized",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -7,
    "meaning": "The destination is not authorised by the asset's issuer to hold it. Some issuers require approval per account."
  },
  {
    "slug": "stellar-path-payment-strict-receive-offer-cross-self",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -11,
    "meaning": "The path would have matched against this account's own offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-path-payment-strict-receive-over-sendmax",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -12,
    "meaning": "The swap would have cost more than the maximum you set, so Stellar refused it rather than spending more than you allowed. That maximum is your slippage protection doing its job: the price along the path moved between the quote and the transaction being applied. Nothing was swapped and only the fee was spent."
  },
  {
    "slug": "stellar-path-payment-strict-receive-src-no-trust",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -3,
    "meaning": "The sending account has no trustline for the asset it tried to send, so it cannot hold or send it."
  },
  {
    "slug": "stellar-path-payment-strict-receive-too-few-offers",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -10,
    "meaning": "There was not enough liquidity along any path to complete this swap. Nothing was swapped."
  },
  {
    "slug": "stellar-path-payment-strict-receive-underfunded",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -2,
    "meaning": "The sending account did not hold enough of the asset being sent. On Stellar this includes the reserve: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so a visible balance is not always a spendable one."
  },
  {
    "slug": "stellar-path-payment-strict-send-line-full",
    "message": "PATH_PAYMENT_STRICT_SEND_LINE_FULL",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over. The recipient sets that limit and can raise it."
  },
  {
    "slug": "stellar-path-payment-strict-send-malformed",
    "message": "PATH_PAYMENT_STRICT_SEND_MALFORMED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -1,
    "meaning": "The swap was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-path-payment-strict-send-no-destination",
    "message": "PATH_PAYMENT_STRICT_SEND_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created before it can be paid."
  },
  {
    "slug": "stellar-path-payment-strict-send-no-trust",
    "message": "PATH_PAYMENT_STRICT_SEND_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -6,
    "meaning": "The destination has no trustline for the asset being delivered. On Stellar an account has to explicitly trust an asset before it can receive it, so this is something the recipient sets up, not a problem with the payment."
  },
  {
    "slug": "stellar-path-payment-strict-send-not-authorized",
    "message": "PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -7,
    "meaning": "The destination is not authorised by the asset's issuer to hold it. Some issuers require approval per account."
  },
  {
    "slug": "stellar-path-payment-strict-send-offer-cross-self",
    "message": "PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -11,
    "meaning": "The path would have matched against this account's own offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-path-payment-strict-send-src-no-trust",
    "message": "PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -3,
    "meaning": "The sending account has no trustline for the asset it tried to send, so it cannot hold or send it."
  },
  {
    "slug": "stellar-path-payment-strict-send-too-few-offers",
    "message": "PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -10,
    "meaning": "There was not enough liquidity along any path to complete this swap. Nothing was swapped."
  },
  {
    "slug": "stellar-path-payment-strict-send-under-destmin",
    "message": "PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -12,
    "meaning": "The swap would have delivered less than the minimum you set, so Stellar refused it rather than filling at a worse rate. That minimum is your slippage protection doing its job: the price along the path moved between the quote and the transaction being applied. Nothing was swapped and only the fee was spent."
  },
  {
    "slug": "stellar-path-payment-strict-send-underfunded",
    "message": "PATH_PAYMENT_STRICT_SEND_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -2,
    "meaning": "The sending account did not hold enough of the asset being sent. On Stellar this includes the reserve: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so a visible balance is not always a spendable one."
  },
  {
    "slug": "stellar-payment-line-full",
    "message": "PAYMENT_LINE_FULL",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over."
  },
  {
    "slug": "stellar-payment-malformed",
    "message": "PAYMENT_MALFORMED",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -1,
    "meaning": "The payment was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-payment-no-destination",
    "message": "PAYMENT_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created and funded before it can be paid."
  },
  {
    "slug": "stellar-payment-no-trust",
    "message": "PAYMENT_NO_TRUST",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -6,
    "meaning": "The destination has no trustline for this asset. On Stellar an account has to explicitly trust an asset before it can receive it, so the recipient sets this up."
  },
  {
    "slug": "stellar-payment-underfunded",
    "message": "PAYMENT_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -2,
    "meaning": "The account did not hold enough of this asset to send that amount. On Stellar the reserve counts against you: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so the spendable balance is lower than the one displayed."
  },
  {
    "slug": "stellar-set-options-low-reserve",
    "message": "SET_OPTIONS_LOW_RESERVE",
    "chain": "stellar",
    "scope": "SET_OPTIONS",
    "code": -1,
    "meaning": "This change would take the account below its minimum reserve. Adding a signer raises the XLM an account must keep, so more XLM is needed first."
  },
  {
    "slug": "stellar-set-trust-line-flags-cant-revoke",
    "message": "SET_TRUST_LINE_FLAGS_CANT_REVOKE",
    "chain": "stellar",
    "scope": "SET_TRUST_LINE_FLAGS",
    "code": -3,
    "meaning": "The issuer has given up the ability to revoke authorisation on this asset, so the flag cannot be cleared."
  },
  {
    "slug": "stellar-set-trust-line-flags-no-trust-line",
    "message": "SET_TRUST_LINE_FLAGS_NO_TRUST_LINE",
    "chain": "stellar",
    "scope": "SET_TRUST_LINE_FLAGS",
    "code": -2,
    "meaning": "There is no trustline between that account and this asset, so its flags could not be set."
  },
  {
    "slug": "stellar-tx-bad-auth",
    "message": "txBAD_AUTH",
    "chain": "stellar",
    "scope": null,
    "code": -6,
    "meaning": "The signatures on this transaction did not meet the account's signing requirements. Nothing was applied."
  },
  {
    "slug": "stellar-tx-bad-seq",
    "message": "txBAD_SEQ",
    "chain": "stellar",
    "scope": null,
    "code": -5,
    "meaning": "The sequence number was not the one this account expected next. That normally means two transactions were submitted from the same account at once, or one was already applied. Reloading the account and rebuilding the transaction fixes it. Nothing was applied here."
  },
  {
    "slug": "stellar-tx-failed",
    "message": "txFAILED",
    "chain": "stellar",
    "scope": null,
    "code": -1,
    "meaning": "One of the operations in this transaction failed, so the whole transaction was rolled back. Stellar applies a transaction all or nothing, so nothing it set out to do took effect."
  },
  {
    "slug": "stellar-tx-fee-bump-inner-failed",
    "message": "txFEE_BUMP_INNER_FAILED",
    "chain": "stellar",
    "scope": null,
    "code": -13,
    "meaning": "This was a fee bump transaction, and the inner transaction it was paying for is the one that failed. The fee bump itself was fine, so look at the inner transaction's own result for the reason."
  },
  {
    "slug": "stellar-tx-insufficient-balance",
    "message": "txINSUFFICIENT_BALANCE",
    "chain": "stellar",
    "scope": null,
    "code": -7,
    "meaning": "The account could not cover the fee while keeping its minimum reserve. On Stellar an account must always hold a base reserve plus an amount for each trustline, offer and signer, so an account can show a balance and still be unable to spend it."
  },
  {
    "slug": "stellar-tx-insufficient-fee",
    "message": "txINSUFFICIENT_FEE",
    "chain": "stellar",
    "scope": null,
    "code": -9,
    "meaning": "The fee offered was below what the network was accepting when this was submitted. Stellar prices by surge when a ledger is full, so a fee that works normally can be too low for a busy ledger. Nothing was applied, and resubmitting with a higher fee is the fix."
  },
  {
    "slug": "stellar-tx-internal-error",
    "message": "txINTERNAL_ERROR",
    "chain": "stellar",
    "scope": null,
    "code": -11,
    "meaning": "The network reported an internal error applying this transaction. Nothing was applied."
  },
  {
    "slug": "stellar-tx-malformed",
    "message": "txMALFORMED",
    "chain": "stellar",
    "scope": null,
    "code": -16,
    "meaning": "The transaction was not well formed, so the network rejected it without applying anything."
  },
  {
    "slug": "stellar-tx-no-account",
    "message": "txNO_ACCOUNT",
    "chain": "stellar",
    "scope": null,
    "code": -8,
    "meaning": "The source account does not exist on the ledger. A Stellar account has to be created and funded before it can send anything."
  },
  {
    "slug": "stellar-tx-soroban-invalid",
    "message": "txSOROBAN_INVALID",
    "chain": "stellar",
    "scope": null,
    "code": -17,
    "meaning": "The Soroban resources declared by this transaction were not valid, so it was rejected before running."
  },
  {
    "slug": "stellar-tx-too-early",
    "message": "txTOO_EARLY",
    "chain": "stellar",
    "scope": null,
    "code": -2,
    "meaning": "The transaction carried a time bound that had not started yet, so the network would not apply it."
  },
  {
    "slug": "stellar-tx-too-late",
    "message": "txTOO_LATE",
    "chain": "stellar",
    "scope": null,
    "code": -3,
    "meaning": "The transaction expired before it was included. Stellar transactions carry a time bound, and this one passed while it was waiting, so it was never applied and nothing moved. Submitting again is safe: the expired one cannot execute later."
  }
]
