// GENERATED by chain-errors.test.ts. Do not edit by hand.
//
// Every entry is the SAME string the decoder uses, read from the chain
// packages rather than retyped, so a published page cannot describe an error
// differently from the product. The test that wrote this file fails if the two
// ever disagree.
//
// Regenerate: UPDATE_CHAIN_ERRORS=1 pnpm --filter @txid/web test

export interface ChainError {
  slug: string
  /** The exact constant a wallet, explorer or SDK shows. The page H1. */
  message: string
  chain: string
  /** The operation the code belongs to, when it is operation-level. */
  scope: string | null
  /** Its signed number within its enum, which is what raw XDR carries. */
  code: number | null
  meaning: string
}

export const CHAIN_ERRORS: ChainError[] = [
  {
    "slug": "aptos-aptos-governance-ealready-voted",
    "message": "EALREADY_VOTED",
    "chain": "aptos",
    "scope": "aptos_governance",
    "code": 2,
    "meaning": "This wallet has already voted on this proposal, and each wallet can vote only once. No action is needed."
  },
  {
    "slug": "aptos-aptos-governance-elock-has-not-expired",
    "message": "ELOCK_HAS_NOT_EXPIRED",
    "chain": "aptos",
    "scope": "aptos_governance",
    "code": 3,
    "meaning": "Your governance lock has not expired yet, so the tokens cannot be unlocked. Wait until the lock period ends and try again."
  },
  {
    "slug": "aptos-aptos-governance-eno-tokens-locked",
    "message": "ENO_TOKENS_LOCKED",
    "chain": "aptos",
    "scope": "aptos_governance",
    "code": 1,
    "meaning": "This wallet has no tokens locked for Amnis governance, so there is nothing to vote with or unlock. Lock tokens first."
  },
  {
    "slug": "aptos-async-matching-engine-einvalid-stop-price",
    "message": "EINVALID_STOP_PRICE",
    "chain": "aptos",
    "scope": "async_matching_engine",
    "code": 4,
    "meaning": "The stop/trigger price on this order is invalid for the current market price, for example a stop that would trigger immediately or on the wrong side. Check the trigger side and price against the market and retry."
  },
  {
    "slug": "aptos-async-matching-engine-einvalid-tp-sl-for-reduce-only",
    "message": "EINVALID_TP_SL_FOR_REDUCE_ONLY",
    "chain": "aptos",
    "scope": "async_matching_engine",
    "code": 2,
    "meaning": "A take-profit/stop-loss cannot be attached to a reduce-only order. Place the reduce-only order without TP/SL, or set the TP/SL on the position itself."
  },
  {
    "slug": "aptos-async-matching-engine-einvalid-tp-sl-with-trigger-condition",
    "message": "EINVALID_TP_SL_WITH_TRIGGER_CONDITION",
    "chain": "aptos",
    "scope": "async_matching_engine",
    "code": 3,
    "meaning": "A take-profit/stop-loss cannot be combined with a stop/trigger price on the same order. Place the triggered order first, then set TP/SL on the resulting position."
  },
  {
    "slug": "aptos-builder-code-registry-ebuilder-not-registered",
    "message": "EBUILDER_NOT_REGISTERED",
    "chain": "aptos",
    "scope": "builder_code_registry",
    "code": 2,
    "meaning": "The builder code attached to this order is not registered with Decibel. This is an integration issue with the app that routed your order, not your account; report it to that app's team or trade from the official interface."
  },
  {
    "slug": "aptos-builder-code-registry-einvalid-amount",
    "message": "EINVALID_AMOUNT",
    "chain": "aptos",
    "scope": "builder_code_registry",
    "code": 1,
    "meaning": "The builder fee on this order is zero or negative, which is not valid. This comes from the app that routed your order; retry from the official interface or report it to that app's team."
  },
  {
    "slug": "aptos-builder-code-registry-einvalid-max-fee",
    "message": "EINVALID_MAX_FEE",
    "chain": "aptos",
    "scope": "builder_code_registry",
    "code": 4,
    "meaning": "The builder fee on this order exceeds the maximum fee you approved for that app. Review the app's fee settings, or approve a higher maximum builder fee if you trust it."
  },
  {
    "slug": "aptos-bulk-order-utils-eprice-crossing",
    "message": "EPRICE_CROSSING",
    "chain": "aptos",
    "scope": "bulk_order_utils",
    "code": 1,
    "meaning": "The bulk order was rejected because its buy and sell prices cross each other: at least one bid was priced at or above one of the asks in the same submission, which would have the order trade against itself. Nothing was placed and only gas was spent. Adjust the ladder so every bid sits strictly below every ask, then resubmit. If you are using automatic repricing, the quotes most likely moved between building the order and submitting it, so rebuild from a fresh mid price."
  },
  {
    "slug": "aptos-clearinghouse-perp-einvalid-argument",
    "message": "EINVALID_ARGUMENT",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 1,
    "meaning": "An argument in this order was invalid (for bulk orders this usually means the price and size lists do not line up). Rebuild the order in the app and retry; if it keeps happening, report it to the team."
  },
  {
    "slug": "aptos-clearinghouse-perp-einvalid-price-is-too-large",
    "message": "EINVALID_PRICE_IS_TOO_LARGE",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 5,
    "meaning": "The order price is larger than the exchange can process. Check the price for typos and retry."
  },
  {
    "slug": "aptos-clearinghouse-perp-einvalid-price-is-zero",
    "message": "EINVALID_PRICE_IS_ZERO",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 4,
    "meaning": "The order price worked out to zero, which is not a valid price. Check the price and retry."
  },
  {
    "slug": "aptos-clearinghouse-perp-einvalid-size-is-too-large",
    "message": "EINVALID_SIZE_IS_TOO_LARGE",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 3,
    "meaning": "The order size is larger than the exchange can process. Reduce the size and retry."
  },
  {
    "slug": "aptos-clearinghouse-perp-einvalid-size-is-zero",
    "message": "EINVALID_SIZE_IS_ZERO",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 2,
    "meaning": "The order or settlement size worked out to zero, so there was nothing to execute. Check the size and retry."
  },
  {
    "slug": "aptos-clearinghouse-perp-enot-reduce-only",
    "message": "ENOT_REDUCE_ONLY",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 8,
    "meaning": "The order was marked reduce-only but would have increased your position instead of reducing it. A reduce-only order can only close or shrink an open position: check the order's side and size against your current position."
  },
  {
    "slug": "aptos-clearinghouse-perp-eself-trade-not-allowed",
    "message": "ESELF_TRADE_NOT_ALLOWED",
    "chain": "aptos",
    "scope": "clearinghouse_perp",
    "code": 7,
    "meaning": "The order would have matched against your own resting order on the other side of the book, which Decibel does not allow. Cancel the opposing order first, or adjust the price so it does not cross your own quote."
  },
  {
    "slug": "aptos-delegation-manager-estake-pool-does-not-exist",
    "message": "ESTAKE_POOL_DOES_NOT_EXIST",
    "chain": "aptos",
    "scope": "delegation_manager",
    "code": 1,
    "meaning": "The stake pool this operation targets does not exist. This is a protocol configuration issue rather than a user mistake; if you hit this from the Amnis app, report it to the team."
  },
  {
    "slug": "aptos-delegation-manager-estake-pool-not-whitelisted",
    "message": "ESTAKE_POOL_NOT_WHITELISTED",
    "chain": "aptos",
    "scope": "delegation_manager",
    "code": 2,
    "meaning": "The target stake pool is not whitelisted by Amnis. This is a protocol configuration issue rather than a user mistake; if you hit this from the Amnis app, report it to the team."
  },
  {
    "slug": "aptos-delegation-manager-eunstake-amount-too-large",
    "message": "EUNSTAKE_AMOUNT_TOO_LARGE",
    "chain": "aptos",
    "scope": "delegation_manager",
    "code": 4,
    "meaning": "You tried to unstake more than is currently staked for you in this pool. Check your staked balance and retry with a smaller amount."
  },
  {
    "slug": "aptos-dex-accounts-enot-subaccount-owner-or-lacks-perp-trading-permissions",
    "message": "ENOT_SUBACCOUNT_OWNER_OR_LACKS_PERP_TRADING_PERMISSIONS",
    "chain": "aptos",
    "scope": "dex_accounts",
    "code": 3,
    "meaning": "The signing wallet does not own this subaccount and has not been granted trading permission on it. Switch to the wallet that owns the subaccount, or have the owner grant this wallet trading permissions, then retry."
  },
  {
    "slug": "aptos-dex-accounts-esubaccount-is-not-active",
    "message": "ESUBACCOUNT_IS_NOT_ACTIVE",
    "chain": "aptos",
    "scope": "dex_accounts",
    "code": 8,
    "meaning": "This subaccount is not active, so it cannot place or cancel orders. In the app, check which subaccount you are trading from and switch to an active one."
  },
  {
    "slug": "aptos-order-placement-utils-einvalid-match-count",
    "message": "EINVALID_MATCH_COUNT",
    "chain": "aptos",
    "scope": "order_placement_utils",
    "code": 1,
    "meaning": "The order failed an internal match-count check in the matching engine. This is a protocol-side condition rather than something you did wrong. Retry the order; if it keeps failing, report it to the team."
  },
  {
    "slug": "aptos-pending-order-tracker-e-invalid-reduce-only-order",
    "message": "E_INVALID_REDUCE_ONLY_ORDER",
    "chain": "aptos",
    "scope": "pending_order_tracker",
    "code": 5,
    "meaning": "The reduce-only order is invalid against your current position, usually because the position is already closed or smaller than the order size. Refresh the position and adjust the order."
  },
  {
    "slug": "aptos-pending-order-tracker-e-market-not-found",
    "message": "E_MARKET_NOT_FOUND",
    "chain": "aptos",
    "scope": "pending_order_tracker",
    "code": 2,
    "meaning": "The cancel request referenced a market where this subaccount has no pending orders. The order may have already filled or been cancelled: refresh your open orders before retrying."
  },
  {
    "slug": "aptos-pending-order-tracker-einvalid-tp-sl-size",
    "message": "EINVALID_TP_SL_SIZE",
    "chain": "aptos",
    "scope": "pending_order_tracker",
    "code": 10,
    "meaning": "The take-profit/stop-loss size is invalid for the position (zero, or larger than the position). Adjust the TP/SL size to at most the open position size."
  },
  {
    "slug": "aptos-pending-order-tracker-emax-fixed-sized-pending-reqs-hit",
    "message": "EMAX_FIXED_SIZED_PENDING_REQS_HIT",
    "chain": "aptos",
    "scope": "pending_order_tracker",
    "code": 8,
    "meaning": "This subaccount already has the maximum number of pending requests, so new ones are rejected until some settle or are cancelled. Cancel pending orders you no longer need, or wait a moment for the queue to clear."
  },
  {
    "slug": "aptos-perp-engine-emarket-halted",
    "message": "EMARKET_HALTED",
    "chain": "aptos",
    "scope": "perp_engine",
    "code": 4,
    "meaning": "This market is currently halted, so orders cannot be placed or cancelled right now. This is an exchange-side pause, not a problem with your account or funds. Wait for trading to resume and retry."
  },
  {
    "slug": "aptos-perp-market-config-einvalid-price",
    "message": "EINVALID_PRICE",
    "chain": "aptos",
    "scope": "perp_market_config",
    "code": 10,
    "meaning": "The order price is zero or invalid for this market. Enter a valid price and retry."
  },
  {
    "slug": "aptos-perp-market-config-eorder-size-too-large",
    "message": "EORDER_SIZE_TOO_LARGE",
    "chain": "aptos",
    "scope": "perp_market_config",
    "code": 12,
    "meaning": "The order's notional value (price multiplied by size) is larger than this market allows. Reduce the order size and retry."
  },
  {
    "slug": "aptos-perp-market-config-eprice-not-respecting-ticker-size",
    "message": "EPRICE_NOT_RESPECTING_TICKER_SIZE",
    "chain": "aptos",
    "scope": "perp_market_config",
    "code": 6,
    "meaning": "The limit price is not a multiple of this market's tick size, so the order was rejected. Round the price to the nearest valid tick and retry."
  },
  {
    "slug": "aptos-perp-market-config-eprice-sizes-length-mismatch",
    "message": "EPRICE_SIZES_LENGTH_MISMATCH",
    "chain": "aptos",
    "scope": "perp_market_config",
    "code": 13,
    "meaning": "The bulk order's price list and size list have different lengths. This is an integration bug in the client that built the order, not a user mistake; report it to the team behind that client."
  },
  {
    "slug": "aptos-perp-market-config-esize-not-respecting-min-size",
    "message": "ESIZE_NOT_RESPECTING_MIN_SIZE",
    "chain": "aptos",
    "scope": "perp_market_config",
    "code": 4,
    "meaning": "The order size is below this market's minimum order size. Increase the size to at least the market minimum and retry."
  },
  {
    "slug": "aptos-position-tp-sl-einvalid-tp-sl-order-id",
    "message": "EINVALID_TP_SL_ORDER_ID",
    "chain": "aptos",
    "scope": "position_tp_sl",
    "code": 65552,
    "meaning": "The take-profit/stop-loss order id in this request does not match any live TP/SL order on the position. The order was most likely already triggered or cancelled, or it belongs to a different position. Refresh the position in the app and check its active TP/SL orders; if the order is gone from the list, there is nothing left to cancel."
  },
  {
    "slug": "aptos-router-e-input-more-than-max",
    "message": "E_INPUT_MORE_THAN_MAX",
    "chain": "aptos",
    "scope": "router",
    "code": 1,
    "meaning": "The swap stopped because it would have needed more input tokens than the maximum your slippage setting allows. The price moved against you between quoting and signing. Nothing was swapped. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "aptos-router-e-insufficient-x-amount",
    "message": "E_INSUFFICIENT_X_AMOUNT",
    "chain": "aptos",
    "scope": "router",
    "code": 2,
    "meaning": "Adding liquidity failed because the amount of the first token in the pair would have fallen below the minimum you set. The pool's ratio shifted since the quote. Retry the deposit, or loosen the minimum amounts slightly."
  },
  {
    "slug": "aptos-router-e-insufficient-y-amount",
    "message": "E_INSUFFICIENT_Y_AMOUNT",
    "chain": "aptos",
    "scope": "router",
    "code": 3,
    "meaning": "Adding liquidity failed because the amount of the second token in the pair would have fallen below the minimum you set. The pool's ratio shifted since the quote. Retry the deposit, or loosen the minimum amounts slightly."
  },
  {
    "slug": "aptos-router-e-output-less-than-min",
    "message": "E_OUTPUT_LESS_THAN_MIN",
    "chain": "aptos",
    "scope": "router",
    "code": 0,
    "meaning": "The swap stopped because the amount you would have received fell below the minimum your slippage setting allows. The price moved between quoting and signing. Nothing was swapped and only gas was spent. Retry the swap; if it keeps happening, raise your slippage tolerance slightly or trade a smaller amount."
  },
  {
    "slug": "aptos-router-e-pair-not-created",
    "message": "E_PAIR_NOT_CREATED",
    "chain": "aptos",
    "scope": "router",
    "code": 4,
    "meaning": "No liquidity pool exists for this token pair on PancakeSwap, so the trade has no route. Double-check both tokens are the ones you meant. If the pair genuinely has no pool, it cannot be swapped here."
  },
  {
    "slug": "aptos-router-einsufficient-amount",
    "message": "EINSUFFICIENT_AMOUNT",
    "chain": "aptos",
    "scope": "router",
    "code": 1,
    "meaning": "The amount is below the minimum Amnis accepts for this operation, so nothing was staked or moved. Increase the amount and retry."
  },
  {
    "slug": "aptos-router-einsufficient-deposit-amount",
    "message": "EINSUFFICIENT_DEPOSIT_AMOUNT",
    "chain": "aptos",
    "scope": "router",
    "code": 2,
    "meaning": "The deposit is below the minimum deposit Amnis accepts. Deposit a slightly larger amount of APT and retry."
  },
  {
    "slug": "aptos-single-order-book-eorder-not-found",
    "message": "EORDER_NOT_FOUND",
    "chain": "aptos",
    "scope": "single_order_book",
    "code": 2,
    "meaning": "The order id in this request was not on this market's book when the request reached the chain, so there was nothing to act on. This is normal in fast markets, and applies whether the user was cancelling the order or changing its price or size. State that plainly and stop there: the order had already left the book, the transaction aborted so no position or balance was affected, and it cost gas only. Do NOT tell the user to refresh the app to find out. Do NOT say the order was filled, and do NOT say it was cancelled either: this abort proves only that the order was ABSENT, never why, and asserting either one is a claim about the user's position that nothing here establishes. Do not offer a next step you cannot ground. If the user asks what to do now, explain that it turns on whether the original filled or was cancelled, since re-placing an order that already filled would trade a second time, and that this has to be checked before acting."
  },
  {
    "slug": "aptos-spot-order-public-api-einsufficient-pfs-funds",
    "message": "EINSUFFICIENT_PFS_FUNDS",
    "chain": "aptos",
    "scope": "spot_order_public_api",
    "code": 1,
    "meaning": "This spot order was rejected because the wallet's available balance is short on one side of the pair: either not enough of the asset being sold, or not enough of the quote asset to buy with. The check runs before anything is placed, so nothing was traded and only gas was spent. Top up the wallet, or reduce the order size, and retry."
  },
  {
    "slug": "aptos-stable-pool-scripts-err-excessive-input",
    "message": "ERR_EXCESSIVE_INPUT",
    "chain": "aptos",
    "scope": "stable_pool_scripts",
    "code": 2,
    "meaning": "The swap was cancelled because it would have needed more input tokens than the maximum your slippage setting allows. The pool price moved against you. Nothing was swapped. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "aptos-stable-pool-scripts-err-insufficient-output",
    "message": "ERR_INSUFFICIENT_OUTPUT",
    "chain": "aptos",
    "scope": "stable_pool_scripts",
    "code": 1,
    "meaning": "The swap was cancelled because the amount you would have received fell below the minimum your slippage setting allows. The pool price moved between quoting and signing. Nothing was swapped and only gas was spent. Retry the swap; if it keeps happening, raise your slippage tolerance slightly or trade a smaller amount."
  },
  {
    "slug": "aptos-swap-error-insufficient-amount",
    "message": "ERROR_INSUFFICIENT_AMOUNT",
    "chain": "aptos",
    "scope": "swap",
    "code": 6,
    "meaning": "An amount in this operation was zero or too small for the pool to process. Check the amounts you entered and retry with larger values."
  },
  {
    "slug": "aptos-swap-error-insufficient-input-amount",
    "message": "ERROR_INSUFFICIENT_INPUT_AMOUNT",
    "chain": "aptos",
    "scope": "swap",
    "code": 14,
    "meaning": "The swap was given a zero or too-small input amount. Enter a larger amount and retry."
  },
  {
    "slug": "aptos-swap-error-insufficient-liquidity",
    "message": "ERROR_INSUFFICIENT_LIQUIDITY",
    "chain": "aptos",
    "scope": "swap",
    "code": 7,
    "meaning": "The pool does not hold enough liquidity for this trade size. Try a smaller amount, or use a pair with deeper liquidity."
  },
  {
    "slug": "aptos-swap-error-insufficient-liquidity-burned",
    "message": "ERROR_INSUFFICIENT_LIQUIDITY_BURNED",
    "chain": "aptos",
    "scope": "swap",
    "code": 10,
    "meaning": "The liquidity withdrawal was too small to redeem anything from the pool. Remove a larger share of your position and retry."
  },
  {
    "slug": "aptos-swap-error-insufficient-liquidity-minted",
    "message": "ERROR_INSUFFICIENT_LIQUIDITY_MINTED",
    "chain": "aptos",
    "scope": "swap",
    "code": 4,
    "meaning": "The liquidity deposit was too small to mint any LP tokens. Deposit larger amounts of both tokens and retry."
  },
  {
    "slug": "aptos-swap-error-insufficient-output-amount",
    "message": "ERROR_INSUFFICIENT_OUTPUT_AMOUNT",
    "chain": "aptos",
    "scope": "swap",
    "code": 13,
    "meaning": "The swap would have produced zero output tokens, usually because the trade size is far too small for this pool. Increase the amount and retry."
  },
  {
    "slug": "aptos-swap-error-invalid-amount",
    "message": "ERROR_INVALID_AMOUNT",
    "chain": "aptos",
    "scope": "swap",
    "code": 8,
    "meaning": "The amount requested is more than the pool can pay out. Reduce the amount and retry."
  },
  {
    "slug": "aptos-swap-error-k",
    "message": "ERROR_K",
    "chain": "aptos",
    "scope": "swap",
    "code": 15,
    "meaning": "The pool's invariant check failed after the swap. This usually means one of the tokens charges a fee or behaves unusually on transfer. Retry with higher slippage; if it keeps failing, that token is likely incompatible with this pool."
  },
  {
    "slug": "aptos-swap-error-tokens-not-sorted",
    "message": "ERROR_TOKENS_NOT_SORTED",
    "chain": "aptos",
    "scope": "swap",
    "code": 9,
    "meaning": "The pair was called with its tokens in the wrong internal order. This is an integration bug in the app that built the transaction, not a user mistake. Report it to the site you used; the official PancakeSwap interface builds this correctly."
  },
  {
    "slug": "aptos-swap-error-x-not-registered",
    "message": "ERROR_X_NOT_REGISTERED",
    "chain": "aptos",
    "scope": "swap",
    "code": 16,
    "meaning": "Your wallet has not registered one of the two tokens in this pair, so it cannot hold it yet (PancakeSwap uses the same code for either token). Register the token in your wallet, or use PancakeSwap's register button for that token, then retry."
  },
  {
    "slug": "aptos-swap-utils-error-insufficient-amount",
    "message": "ERROR_INSUFFICIENT_AMOUNT",
    "chain": "aptos",
    "scope": "swap_utils",
    "code": 2,
    "meaning": "An amount in this operation was zero or too small for the pool to process. Check the amounts you entered and retry with larger values."
  },
  {
    "slug": "aptos-swap-utils-error-insufficient-input-amount",
    "message": "ERROR_INSUFFICIENT_INPUT_AMOUNT",
    "chain": "aptos",
    "scope": "swap_utils",
    "code": 0,
    "meaning": "The swap was given a zero or too-small input amount. Enter a larger amount and retry."
  },
  {
    "slug": "aptos-swap-utils-error-insufficient-liquidity",
    "message": "ERROR_INSUFFICIENT_LIQUIDITY",
    "chain": "aptos",
    "scope": "swap_utils",
    "code": 1,
    "meaning": "The pool for this pair has no usable liquidity right now, so a price cannot be computed. Try a smaller amount or a different pair."
  },
  {
    "slug": "aptos-swap-utils-error-insufficient-outpot-amount",
    "message": "ERROR_INSUFFICIENT_OUTPOT_AMOUNT",
    "chain": "aptos",
    "scope": "swap_utils",
    "code": 3,
    "meaning": "The swap would have produced zero output tokens, usually because the trade size is far too small for this pool. Increase the amount and retry."
  },
  {
    "slug": "aptos-swap-utils-error-same-coin",
    "message": "ERROR_SAME_COIN",
    "chain": "aptos",
    "scope": "swap_utils",
    "code": 4,
    "meaning": "The swap was asked to trade a token for itself. Pick two different tokens and retry."
  },
  {
    "slug": "aptos-tp-sl-utils-einvalid-tp-sl-parameters",
    "message": "EINVALID_TP_SL_PARAMETERS",
    "chain": "aptos",
    "scope": "tp_sl_utils",
    "code": 1,
    "meaning": "The take-profit/stop-loss parameters are invalid, usually a TP or SL price on the wrong side of the current price. For a long, take-profit must be above and stop-loss below the price (reversed for a short). Fix the prices and retry."
  },
  {
    "slug": "aptos-weighted-pool-scripts-err-excessive-input",
    "message": "ERR_EXCESSIVE_INPUT",
    "chain": "aptos",
    "scope": "weighted_pool_scripts",
    "code": 2,
    "meaning": "The swap was cancelled because it would have needed more input tokens than the maximum your slippage setting allows. The pool price moved against you. Nothing was swapped. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "aptos-weighted-pool-scripts-err-insufficient-output",
    "message": "ERR_INSUFFICIENT_OUTPUT",
    "chain": "aptos",
    "scope": "weighted_pool_scripts",
    "code": 1,
    "meaning": "The swap was cancelled because the amount you would have received fell below the minimum your slippage setting allows. The pool price moved between quoting and signing. Nothing was swapped and only gas was spent. Retry the swap; if it keeps happening, raise your slippage tolerance slightly or trade a smaller amount."
  },
  {
    "slug": "aptos-withdrawal-enot-withdrawal-token-owner",
    "message": "ENOT_WITHDRAWAL_TOKEN_OWNER",
    "chain": "aptos",
    "scope": "withdrawal",
    "code": 2,
    "meaning": "The withdrawal ticket you tried to claim belongs to a different wallet. Switch to the wallet that requested the withdrawal and claim from there."
  },
  {
    "slug": "aptos-withdrawal-etoken-lock-not-expired",
    "message": "ETOKEN_LOCK_NOT_EXPIRED",
    "chain": "aptos",
    "scope": "withdrawal",
    "code": 1,
    "meaning": "This withdrawal is still inside its unbonding period, so it cannot be claimed yet. Wait until the lockup shown on your withdrawal ticket ends, then claim again."
  },
  {
    "slug": "hyperliquid-bad-alo-px-rejected",
    "message": "badAloPxRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The order was add-liquidity-only, and its price would have crossed the book and taken liquidity instead of adding it. Add-liquidity-only exists to guarantee the maker fee, so rather than filling at taker terms the order is refused. The market moved between the price being chosen and the order arriving."
  },
  {
    "slug": "hyperliquid-canceled",
    "message": "canceled",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The order was cancelled. On Hyperliquid this is the trader's own cancellation, so if the user did not cancel it, an app or a bot acting for them did."
  },
  {
    "slug": "hyperliquid-insufficient-spot-balance-rejected",
    "message": "insufficientSpotBalanceRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "There was not enough of the spot asset to place this order. Spot and perpetual balances are held separately on Hyperliquid, so funds sitting on the perpetuals side do not back a spot order until they are transferred."
  },
  {
    "slug": "hyperliquid-ioc-cancel-rejected",
    "message": "iocCancelRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The order was immediate-or-cancel, and there was nothing on the book to fill it at that price, so it was cancelled instead of resting. That is what immediate-or-cancel asks for: fill now or not at all. Nothing was traded."
  },
  {
    "slug": "hyperliquid-min-trade-ntl-rejected",
    "message": "minTradeNtlRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The order was below Hyperliquid's minimum trade value. Every market has a floor in dollars rather than in coins, so a small order in a high-priced asset can be under it even when the quantity looks reasonable. Nothing was traded and nothing was charged."
  },
  {
    "slug": "hyperliquid-perp-margin-rejected",
    "message": "perpMarginRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "There was not enough margin for this perpetual order. Margin is the collateral the position needs, not the account balance, so an account can hold funds and still be unable to open more."
  },
  {
    "slug": "hyperliquid-reduce-only-canceled",
    "message": "reduceOnlyCanceled",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The exchange cancelled this resting reduce-only order because the position it was there to reduce is gone. The trader did not cancel it. Nothing was traded."
  },
  {
    "slug": "hyperliquid-reduce-only-rejected",
    "message": "reduceOnlyRejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The order was marked reduce-only, and there was no position left for it to reduce. That usually means the position had already been closed, or another order closed it first. Nothing was traded."
  },
  {
    "slug": "hyperliquid-rejected",
    "message": "rejected",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "The exchange refused the order without naming a more specific reason. Nothing was traded."
  },
  {
    "slug": "hyperliquid-triggered",
    "message": "triggered",
    "chain": "hyperliquid",
    "scope": null,
    "code": null,
    "meaning": "A stop or take-profit condition was met, so the order was released onto the book."
  },
  {
    "slug": "near-intents-insufficientbalanceoroverflow",
    "message": "insufficient balance or overflow",
    "chain": "near",
    "scope": "intents.near",
    "code": null,
    "meaning": "The account did not hold enough of the token this intent was going to spend, or the amounts involved were too large to process. Nothing was executed."
  },
  {
    "slug": "near-intents-invalidintent",
    "message": "invalid intent",
    "chain": "near",
    "scope": "intents.near",
    "code": null,
    "meaning": "The intent this transaction carried was not one the contract would accept, usually because it had already been used, had expired, or was signed for different terms than the ones submitted. Nothing was executed."
  },
  {
    "slug": "near-v2-ref-finance-e68",
    "message": "E68",
    "chain": "near",
    "scope": "v2.ref-finance.near",
    "code": null,
    "meaning": "The price moved between the swap being quoted and it reaching the pool, by more than the slippage the swap allowed. Ref refuses rather than filling at a worse rate than agreed. Nothing was traded, only the gas was spent, and trying again with a slightly higher slippage tolerance, or a smaller size, usually goes through."
  },
  {
    "slug": "near-v2-ref-finance-e76",
    "message": "E76",
    "chain": "near",
    "scope": "v2.ref-finance.near",
    "code": null,
    "meaning": "The pool did not hold enough of the token being bought to complete this swap at the size requested. A smaller amount, or a different route, will usually go through."
  },
  {
    "slug": "solana-buy-slippage-below-min-base-amount-out",
    "message": "BuySlippageBelowMinBaseAmountOut",
    "chain": "solana",
    "scope": "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
    "code": 6040,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-buy-slippage-below-min-tokens-out",
    "message": "BuySlippageBelowMinTokensOut",
    "chain": "solana",
    "scope": "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
    "code": 6042,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-coin-creator-migrated-to-sharing-config",
    "message": "CoinCreatorMigratedToSharingConfig",
    "chain": "solana",
    "scope": "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
    "code": 6047,
    "meaning": "coin creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead."
  },
  {
    "slug": "solana-creator-vault-migrated-to-sharing-config",
    "message": "CreatorVaultMigratedToSharingConfig",
    "chain": "solana",
    "scope": "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
    "code": 6048,
    "meaning": "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead."
  },
  {
    "slug": "solana-exceeded-amount-slippage-tolerance",
    "message": "ExceededAmountSlippageTolerance",
    "chain": "solana",
    "scope": "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo",
    "code": 6003,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-exceeded-slippage",
    "message": "ExceededSlippage",
    "chain": "solana",
    "scope": "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
    "code": 6004,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-invalid-slippage",
    "message": "InvalidSlippage",
    "chain": "solana",
    "scope": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
    "code": 6004,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-less-than-minimum-amount-out",
    "message": "LessThanMinimumAmountOut",
    "chain": "solana",
    "scope": "T1TANpTeScyeqVzzgNViGDNrkQ6qHz9KrSBS4aNXvGT",
    "code": 6008,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-min-return-not-reached",
    "message": "MinReturnNotReached",
    "chain": "solana",
    "scope": "proVF4pMXVaYqmy4NjniPh4pqKNfMmsihgd4wdkCX3u",
    "code": 6010,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-slippage-limit-exceeded",
    "message": "SlippageLimitExceeded",
    "chain": "solana",
    "scope": "DF1ow4tspfHX9JwWJsAb9epbkA8hmpSEAtxXy1V27QBH",
    "code": 15001,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-slippage-tolerance-exceeded",
    "message": "SlippageToleranceExceeded",
    "chain": "solana",
    "scope": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",
    "code": 6001,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-too-little-sol-received",
    "message": "TooLittleSolReceived",
    "chain": "solana",
    "scope": "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
    "code": 6003,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "solana-too-much-sol-required",
    "message": "TooMuchSolRequired",
    "chain": "solana",
    "scope": "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
    "code": 6002,
    "meaning": "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening."
  },
  {
    "slug": "stellar-account-merge-dest-full",
    "message": "ACCOUNT_MERGE_DEST_FULL",
    "chain": "stellar",
    "scope": "ACCOUNT_MERGE",
    "code": -6,
    "meaning": "Merging would take the destination account past the maximum balance it can hold."
  },
  {
    "slug": "stellar-account-merge-has-sub-entries",
    "message": "ACCOUNT_MERGE_HAS_SUB_ENTRIES",
    "chain": "stellar",
    "scope": "ACCOUNT_MERGE",
    "code": -4,
    "meaning": "The account still has trustlines, offers, signers or data entries, and all of those have to be removed before it can be merged away."
  },
  {
    "slug": "stellar-change-trust-invalid-limit",
    "message": "CHANGE_TRUST_INVALID_LIMIT",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -3,
    "meaning": "The trustline limit given was not valid, for example lower than the balance already held."
  },
  {
    "slug": "stellar-change-trust-low-reserve",
    "message": "CHANGE_TRUST_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -4,
    "meaning": "Adding this trustline would take the account below its minimum reserve. Each trustline raises the XLM an account must keep, so more XLM is needed before it can be added."
  },
  {
    "slug": "stellar-change-trust-not-auth-maintain-liabilities",
    "message": "CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES",
    "chain": "stellar",
    "scope": "CHANGE_TRUST",
    "code": -8,
    "meaning": "The issuer has not authorised this account to maintain liabilities on the asset."
  },
  {
    "slug": "stellar-claim-claimable-balance-cannot-claim",
    "message": "CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -2,
    "meaning": "This account is not able to claim that balance right now. A claimable balance carries conditions, most often a time window, and they were not met."
  },
  {
    "slug": "stellar-claim-claimable-balance-does-not-exist",
    "message": "CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -1,
    "meaning": "There is no claimable balance with that identifier. It may already have been claimed."
  },
  {
    "slug": "stellar-claim-claimable-balance-line-full",
    "message": "CLAIM_CLAIMABLE_BALANCE_LINE_FULL",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -3,
    "meaning": "Claiming this would take the account past the limit on its trustline for the asset."
  },
  {
    "slug": "stellar-claim-claimable-balance-no-trust",
    "message": "CLAIM_CLAIMABLE_BALANCE_NO_TRUST",
    "chain": "stellar",
    "scope": "CLAIM_CLAIMABLE_BALANCE",
    "code": -4,
    "meaning": "The account has no trustline for the asset in this claimable balance, so it cannot receive it."
  },
  {
    "slug": "stellar-create-account-underfunded",
    "message": "CREATE_ACCOUNT_UNDERFUNDED",
    "chain": "stellar",
    "scope": "CREATE_ACCOUNT",
    "code": -2,
    "meaning": "The funding account did not have enough XLM to create the new account with its minimum starting balance."
  },
  {
    "slug": "stellar-create-claimable-balance-low-reserve",
    "message": "CREATE_CLAIMABLE_BALANCE_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -2,
    "meaning": "Creating this claimable balance would take the account below its minimum reserve."
  },
  {
    "slug": "stellar-create-claimable-balance-malformed",
    "message": "CREATE_CLAIMABLE_BALANCE_MALFORMED",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -1,
    "meaning": "The claimable balance was not well formed, for example an invalid amount or claimant."
  },
  {
    "slug": "stellar-create-claimable-balance-no-trust",
    "message": "CREATE_CLAIMABLE_BALANCE_NO_TRUST",
    "chain": "stellar",
    "scope": "CREATE_CLAIMABLE_BALANCE",
    "code": -3,
    "meaning": "The account has no trustline for the asset it tried to lock into a claimable balance."
  },
  {
    "slug": "stellar-invoke-host-function-entry-archived",
    "message": "INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -4,
    "meaning": "The contract data this call needed has been archived. Soroban expires state that has not been used, and it has to be restored before the contract can run again."
  },
  {
    "slug": "stellar-invoke-host-function-insufficient-refundable-fee",
    "message": "INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -5,
    "meaning": "The refundable portion of the fee was not enough to cover the contract's rent and events."
  },
  {
    "slug": "stellar-invoke-host-function-resource-limit-exceeded",
    "message": "INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -3,
    "meaning": "The contract call needed more resources than the transaction reserved for it. On Soroban a transaction declares its resource budget up front, so this is a budget set too low rather than an account short of funds."
  },
  {
    "slug": "stellar-invoke-host-function-trapped",
    "message": "INVOKE_HOST_FUNCTION_TRAPPED",
    "chain": "stellar",
    "scope": "INVOKE_HOST_FUNCTION",
    "code": -2,
    "meaning": "The contract stopped partway through and rejected the call. The reason is defined by the contract rather than by Stellar, so what it means depends on the protocol. Nothing the transaction set out to do took effect."
  },
  {
    "slug": "stellar-liquidity-pool-deposit-bad-price",
    "message": "LIQUIDITY_POOL_DEPOSIT_BAD_PRICE",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_DEPOSIT",
    "code": -6,
    "meaning": "The pool's price moved outside the range this deposit allowed, so it was refused rather than filled at a worse rate."
  },
  {
    "slug": "stellar-liquidity-pool-deposit-no-trust",
    "message": "LIQUIDITY_POOL_DEPOSIT_NO_TRUST",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_DEPOSIT",
    "code": -2,
    "meaning": "The account has no trustline for the pool shares or for one of the pool's assets."
  },
  {
    "slug": "stellar-liquidity-pool-withdraw-under-minimum",
    "message": "LIQUIDITY_POOL_WITHDRAW_UNDER_MINIMUM",
    "chain": "stellar",
    "scope": "LIQUIDITY_POOL_WITHDRAW",
    "code": -5,
    "meaning": "The withdrawal would have returned less than the minimum set, so it was refused. The pool's composition moved between the quote and the transaction being applied."
  },
  {
    "slug": "stellar-manage-buy-offer-buy-no-trust",
    "message": "MANAGE_BUY_OFFER_BUY_NO_TRUST",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -3,
    "meaning": "The account has no trustline for the asset it offered to buy, so it could not receive it."
  },
  {
    "slug": "stellar-manage-buy-offer-cross-self",
    "message": "MANAGE_BUY_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -8,
    "meaning": "This offer would have matched against the account's own existing offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-manage-buy-offer-line-full",
    "message": "MANAGE_BUY_OFFER_LINE_FULL",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -6,
    "meaning": "Filling this offer would take the account past the limit on its trustline for the asset it would receive."
  },
  {
    "slug": "stellar-manage-buy-offer-low-reserve",
    "message": "MANAGE_BUY_OFFER_LOW_RESERVE",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -12,
    "meaning": "Keeping this offer on the book would take the account below its minimum reserve. Each open offer raises the XLM an account must hold."
  },
  {
    "slug": "stellar-manage-buy-offer-malformed",
    "message": "MANAGE_BUY_OFFER_MALFORMED",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -1,
    "meaning": "The offer was not well formed, for example a non-positive amount or an invalid price."
  },
  {
    "slug": "stellar-manage-buy-offer-not-found",
    "message": "MANAGE_BUY_OFFER_NOT_FOUND",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -11,
    "meaning": "The offer this was trying to change or cancel is no longer on the book. It may already have been filled or cancelled."
  },
  {
    "slug": "stellar-manage-buy-offer-underfunded",
    "message": "MANAGE_BUY_OFFER_UNDERFUNDED",
    "chain": "stellar",
    "scope": "MANAGE_BUY_OFFER",
    "code": -7,
    "meaning": "The account does not hold enough of the asset it offered to pay with, once the reserve is taken into account."
  },
  {
    "slug": "stellar-manage-sell-offer-buy-no-trust",
    "message": "MANAGE_SELL_OFFER_BUY_NO_TRUST",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -3,
    "meaning": "The account has no trustline for the asset it offered to buy, so it could not receive it."
  },
  {
    "slug": "stellar-manage-sell-offer-cross-self",
    "message": "MANAGE_SELL_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -8,
    "meaning": "This offer would have matched against the account's own existing offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-manage-sell-offer-line-full",
    "message": "MANAGE_SELL_OFFER_LINE_FULL",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -6,
    "meaning": "Filling this offer would take the account past the limit on its trustline for the asset it would receive."
  },
  {
    "slug": "stellar-manage-sell-offer-low-reserve",
    "message": "MANAGE_SELL_OFFER_LOW_RESERVE",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -12,
    "meaning": "Keeping this offer on the book would take the account below its minimum reserve. Each open offer raises the XLM an account must hold."
  },
  {
    "slug": "stellar-manage-sell-offer-malformed",
    "message": "MANAGE_SELL_OFFER_MALFORMED",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -1,
    "meaning": "The offer was not well formed, for example a non-positive amount or an invalid price."
  },
  {
    "slug": "stellar-manage-sell-offer-not-found",
    "message": "MANAGE_SELL_OFFER_NOT_FOUND",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -11,
    "meaning": "The offer this was trying to change or cancel is no longer on the book. It may already have been filled or cancelled."
  },
  {
    "slug": "stellar-manage-sell-offer-underfunded",
    "message": "MANAGE_SELL_OFFER_UNDERFUNDED",
    "chain": "stellar",
    "scope": "CREATE_PASSIVE_SELL_OFFER",
    "code": -7,
    "meaning": "The account does not hold enough of the asset it offered to sell, once the reserve is taken into account."
  },
  {
    "slug": "stellar-op-too-many-subentries",
    "message": "opTOO_MANY_SUBENTRIES",
    "chain": "stellar",
    "scope": null,
    "code": -4,
    "meaning": "The account already holds the maximum number of subentries (trustlines, offers, signers and data entries), so another could not be added."
  },
  {
    "slug": "stellar-path-payment-strict-receive-line-full",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over. The recipient sets that limit and can raise it."
  },
  {
    "slug": "stellar-path-payment-strict-receive-malformed",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_MALFORMED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -1,
    "meaning": "The swap was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-path-payment-strict-receive-no-destination",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created before it can be paid."
  },
  {
    "slug": "stellar-path-payment-strict-receive-no-trust",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -6,
    "meaning": "The destination has no trustline for the asset being delivered. On Stellar an account has to explicitly trust an asset before it can receive it, so this is something the recipient sets up, not a problem with the payment."
  },
  {
    "slug": "stellar-path-payment-strict-receive-not-authorized",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -7,
    "meaning": "The destination is not authorised by the asset's issuer to hold it. Some issuers require approval per account."
  },
  {
    "slug": "stellar-path-payment-strict-receive-offer-cross-self",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -11,
    "meaning": "The path would have matched against this account's own offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-path-payment-strict-receive-over-sendmax",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -12,
    "meaning": "The swap would have cost more than the maximum you set, so Stellar refused it rather than spending more than you allowed. That maximum is your slippage protection doing its job: the price along the path moved between the quote and the transaction being applied. Nothing was swapped and only the fee was spent."
  },
  {
    "slug": "stellar-path-payment-strict-receive-src-no-trust",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -3,
    "meaning": "The sending account has no trustline for the asset it tried to send, so it cannot hold or send it."
  },
  {
    "slug": "stellar-path-payment-strict-receive-too-few-offers",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -10,
    "meaning": "There was not enough liquidity along any path to complete this swap. Nothing was swapped."
  },
  {
    "slug": "stellar-path-payment-strict-receive-underfunded",
    "message": "PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_RECEIVE",
    "code": -2,
    "meaning": "The sending account did not hold enough of the asset being sent. On Stellar this includes the reserve: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so a visible balance is not always a spendable one."
  },
  {
    "slug": "stellar-path-payment-strict-send-line-full",
    "message": "PATH_PAYMENT_STRICT_SEND_LINE_FULL",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over. The recipient sets that limit and can raise it."
  },
  {
    "slug": "stellar-path-payment-strict-send-malformed",
    "message": "PATH_PAYMENT_STRICT_SEND_MALFORMED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -1,
    "meaning": "The swap was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-path-payment-strict-send-no-destination",
    "message": "PATH_PAYMENT_STRICT_SEND_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created before it can be paid."
  },
  {
    "slug": "stellar-path-payment-strict-send-no-trust",
    "message": "PATH_PAYMENT_STRICT_SEND_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -6,
    "meaning": "The destination has no trustline for the asset being delivered. On Stellar an account has to explicitly trust an asset before it can receive it, so this is something the recipient sets up, not a problem with the payment."
  },
  {
    "slug": "stellar-path-payment-strict-send-not-authorized",
    "message": "PATH_PAYMENT_STRICT_SEND_NOT_AUTHORIZED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -7,
    "meaning": "The destination is not authorised by the asset's issuer to hold it. Some issuers require approval per account."
  },
  {
    "slug": "stellar-path-payment-strict-send-offer-cross-self",
    "message": "PATH_PAYMENT_STRICT_SEND_OFFER_CROSS_SELF",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -11,
    "meaning": "The path would have matched against this account's own offer, which Stellar does not allow."
  },
  {
    "slug": "stellar-path-payment-strict-send-src-no-trust",
    "message": "PATH_PAYMENT_STRICT_SEND_SRC_NO_TRUST",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -3,
    "meaning": "The sending account has no trustline for the asset it tried to send, so it cannot hold or send it."
  },
  {
    "slug": "stellar-path-payment-strict-send-too-few-offers",
    "message": "PATH_PAYMENT_STRICT_SEND_TOO_FEW_OFFERS",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -10,
    "meaning": "There was not enough liquidity along any path to complete this swap. Nothing was swapped."
  },
  {
    "slug": "stellar-path-payment-strict-send-under-destmin",
    "message": "PATH_PAYMENT_STRICT_SEND_UNDER_DESTMIN",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -12,
    "meaning": "The swap would have delivered less than the minimum you set, so Stellar refused it rather than filling at a worse rate. That minimum is your slippage protection doing its job: the price along the path moved between the quote and the transaction being applied. Nothing was swapped and only the fee was spent."
  },
  {
    "slug": "stellar-path-payment-strict-send-underfunded",
    "message": "PATH_PAYMENT_STRICT_SEND_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PATH_PAYMENT_STRICT_SEND",
    "code": -2,
    "meaning": "The sending account did not hold enough of the asset being sent. On Stellar this includes the reserve: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so a visible balance is not always a spendable one."
  },
  {
    "slug": "stellar-payment-line-full",
    "message": "PAYMENT_LINE_FULL",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -8,
    "meaning": "The destination's trustline for this asset has a limit, and this payment would have taken it over."
  },
  {
    "slug": "stellar-payment-malformed",
    "message": "PAYMENT_MALFORMED",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -1,
    "meaning": "The payment was not well formed, for example a non-positive amount or an invalid asset."
  },
  {
    "slug": "stellar-payment-no-destination",
    "message": "PAYMENT_NO_DESTINATION",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -5,
    "meaning": "The destination account does not exist on the ledger. A Stellar account has to be created and funded before it can be paid."
  },
  {
    "slug": "stellar-payment-no-trust",
    "message": "PAYMENT_NO_TRUST",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -6,
    "meaning": "The destination has no trustline for this asset. On Stellar an account has to explicitly trust an asset before it can receive it, so the recipient sets this up."
  },
  {
    "slug": "stellar-payment-underfunded",
    "message": "PAYMENT_UNDERFUNDED",
    "chain": "stellar",
    "scope": "PAYMENT",
    "code": -2,
    "meaning": "The account did not hold enough of this asset to send that amount. On Stellar the reserve counts against you: an account must keep a minimum XLM balance plus an amount for each trustline, offer and signer, so the spendable balance is lower than the one displayed."
  },
  {
    "slug": "stellar-set-options-low-reserve",
    "message": "SET_OPTIONS_LOW_RESERVE",
    "chain": "stellar",
    "scope": "SET_OPTIONS",
    "code": -1,
    "meaning": "This change would take the account below its minimum reserve. Adding a signer raises the XLM an account must keep, so more XLM is needed first."
  },
  {
    "slug": "stellar-set-trust-line-flags-cant-revoke",
    "message": "SET_TRUST_LINE_FLAGS_CANT_REVOKE",
    "chain": "stellar",
    "scope": "SET_TRUST_LINE_FLAGS",
    "code": -3,
    "meaning": "The issuer has given up the ability to revoke authorisation on this asset, so the flag cannot be cleared."
  },
  {
    "slug": "stellar-set-trust-line-flags-no-trust-line",
    "message": "SET_TRUST_LINE_FLAGS_NO_TRUST_LINE",
    "chain": "stellar",
    "scope": "SET_TRUST_LINE_FLAGS",
    "code": -2,
    "meaning": "There is no trustline between that account and this asset, so its flags could not be set."
  },
  {
    "slug": "stellar-tx-bad-auth",
    "message": "txBAD_AUTH",
    "chain": "stellar",
    "scope": null,
    "code": -6,
    "meaning": "The signatures on this transaction did not meet the account's signing requirements. Nothing was applied."
  },
  {
    "slug": "stellar-tx-bad-seq",
    "message": "txBAD_SEQ",
    "chain": "stellar",
    "scope": null,
    "code": -5,
    "meaning": "The sequence number was not the one this account expected next. That normally means two transactions were submitted from the same account at once, or one was already applied. Reloading the account and rebuilding the transaction fixes it. Nothing was applied here."
  },
  {
    "slug": "stellar-tx-failed",
    "message": "txFAILED",
    "chain": "stellar",
    "scope": null,
    "code": -1,
    "meaning": "One of the operations in this transaction failed, so the whole transaction was rolled back. Stellar applies a transaction all or nothing, so nothing it set out to do took effect."
  },
  {
    "slug": "stellar-tx-fee-bump-inner-failed",
    "message": "txFEE_BUMP_INNER_FAILED",
    "chain": "stellar",
    "scope": null,
    "code": -13,
    "meaning": "This was a fee bump transaction, and the inner transaction it was paying for is the one that failed. The fee bump itself was fine, so look at the inner transaction's own result for the reason."
  },
  {
    "slug": "stellar-tx-insufficient-balance",
    "message": "txINSUFFICIENT_BALANCE",
    "chain": "stellar",
    "scope": null,
    "code": -7,
    "meaning": "The account could not cover the fee while keeping its minimum reserve. On Stellar an account must always hold a base reserve plus an amount for each trustline, offer and signer, so an account can show a balance and still be unable to spend it."
  },
  {
    "slug": "stellar-tx-insufficient-fee",
    "message": "txINSUFFICIENT_FEE",
    "chain": "stellar",
    "scope": null,
    "code": -9,
    "meaning": "The fee offered was below what the network was accepting when this was submitted. Stellar prices by surge when a ledger is full, so a fee that works normally can be too low for a busy ledger. Nothing was applied, and resubmitting with a higher fee is the fix."
  },
  {
    "slug": "stellar-tx-internal-error",
    "message": "txINTERNAL_ERROR",
    "chain": "stellar",
    "scope": null,
    "code": -11,
    "meaning": "The network reported an internal error applying this transaction. Nothing was applied."
  },
  {
    "slug": "stellar-tx-malformed",
    "message": "txMALFORMED",
    "chain": "stellar",
    "scope": null,
    "code": -16,
    "meaning": "The transaction was not well formed, so the network rejected it without applying anything."
  },
  {
    "slug": "stellar-tx-no-account",
    "message": "txNO_ACCOUNT",
    "chain": "stellar",
    "scope": null,
    "code": -8,
    "meaning": "The source account does not exist on the ledger. A Stellar account has to be created and funded before it can send anything."
  },
  {
    "slug": "stellar-tx-soroban-invalid",
    "message": "txSOROBAN_INVALID",
    "chain": "stellar",
    "scope": null,
    "code": -17,
    "meaning": "The Soroban resources declared by this transaction were not valid, so it was rejected before running."
  },
  {
    "slug": "stellar-tx-too-early",
    "message": "txTOO_EARLY",
    "chain": "stellar",
    "scope": null,
    "code": -2,
    "meaning": "The transaction carried a time bound that had not started yet, so the network would not apply it."
  },
  {
    "slug": "stellar-tx-too-late",
    "message": "txTOO_LATE",
    "chain": "stellar",
    "scope": null,
    "code": -3,
    "meaning": "The transaction expired before it was included. Stellar transactions carry a time bound, and this one passed while it was waiting, so it was never applied and nothing moved. Submitting again is safe: the expired one cannot execute later."
  },
  {
    "slug": "sui-balance-manager-ebalance-manager-balance-too-low",
    "message": "EBalanceManagerBalanceTooLow",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 3,
    "meaning": "The withdrawal asked for more than the balance manager holds of that coin. Funds in DeepBook sit inside your balance manager rather than in your wallet, and settled trades or open orders can hold part of it, so the amount available to withdraw is not always the amount you deposited."
  },
  {
    "slug": "sui-balance-manager-ecap-not-in-list",
    "message": "ECapNotInList",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 5,
    "meaning": "The capability this transaction tried to use or revoke is not registered on this balance manager. It may already have been revoked."
  },
  {
    "slug": "sui-balance-manager-einvalid-owner",
    "message": "EInvalidOwner",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 0,
    "meaning": "The balance manager this transaction used is not owned by the address that signed it. A balance manager belongs to one owner, and only that owner can act on it directly."
  },
  {
    "slug": "sui-balance-manager-einvalid-proof",
    "message": "EInvalidProof",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 2,
    "meaning": "The trade proof presented with this transaction was not valid for the balance manager it was used against. A proof is generated for one balance manager and one purpose, so this usually means the wrong one was attached."
  },
  {
    "slug": "sui-balance-manager-einvalid-trader",
    "message": "EInvalidTrader",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 1,
    "meaning": "The address that signed is not a trader authorised on this balance manager. The owner grants trading rights explicitly, and this address does not currently hold them."
  },
  {
    "slug": "sui-balance-manager-emax-caps-reached",
    "message": "EMaxCapsReached",
    "chain": "sui",
    "scope": "balance_manager",
    "code": 4,
    "meaning": "This balance manager already has the maximum number of capabilities issued against it, so another could not be added. An existing one has to be revoked first."
  },
  {
    "slug": "sui-big-vector-ebad-redistribution",
    "message": "EBadRedistribution",
    "chain": "sui",
    "scope": "big_vector",
    "code": 9,
    "meaning": "DeepBook stopped on an internal check (a redistribution between orderbook nodes that would have had no effect). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-ebad-remove",
    "message": "EBadRemove",
    "chain": "sui",
    "scope": "big_vector",
    "code": 7,
    "meaning": "DeepBook stopped on an internal check (an orderbook node in an unexpected state during removal). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-eexists",
    "message": "EExists",
    "chain": "sui",
    "scope": "big_vector",
    "code": 6,
    "meaning": "DeepBook stopped on an internal check (a key that already existed in the orderbook structure). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-efan-out-too-big",
    "message": "EFanOutTooBig",
    "chain": "sui",
    "scope": "big_vector",
    "code": 3,
    "meaning": "DeepBook stopped on an internal check (an orderbook fan-out above the allowed maximum). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-efan-out-too-small",
    "message": "EFanOutTooSmall",
    "chain": "sui",
    "scope": "big_vector",
    "code": 2,
    "meaning": "DeepBook stopped on an internal check (an orderbook fan-out below the allowed minimum). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-enot-adjacent",
    "message": "ENotAdjacent",
    "chain": "sui",
    "scope": "big_vector",
    "code": 8,
    "meaning": "DeepBook stopped on an internal check (two orderbook nodes whose links did not match up). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-enot-empty",
    "message": "ENotEmpty",
    "chain": "sui",
    "scope": "big_vector",
    "code": 4,
    "meaning": "DeepBook stopped on an internal check (an orderbook structure expected to be empty and was not). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-enot-found",
    "message": "ENotFound",
    "chain": "sui",
    "scope": "big_vector",
    "code": 5,
    "meaning": "The order this transaction referred to is no longer on the book. An order that has already been filled, cancelled or expired cannot be modified or cancelled again, and DeepBook has no record of it to act on. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-eslice-too-big",
    "message": "ESliceTooBig",
    "chain": "sui",
    "scope": "big_vector",
    "code": 1,
    "meaning": "DeepBook stopped on an internal check (an orderbook slice size above the allowed maximum). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-big-vector-eslice-too-small",
    "message": "ESliceTooSmall",
    "chain": "sui",
    "scope": "big_vector",
    "code": 0,
    "meaning": "DeepBook stopped on an internal check (an orderbook slice size below the allowed minimum). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-book-eempty-orderbook",
    "message": "EEmptyOrderbook",
    "chain": "sui",
    "scope": "book",
    "code": 2,
    "meaning": "There are no resting orders on the side of the book this order needed to match against, so there was nothing to trade with."
  },
  {
    "slug": "sui-book-einvalid-amount-in",
    "message": "EInvalidAmountIn",
    "chain": "sui",
    "scope": "book",
    "code": 1,
    "meaning": "The input amount for this swap was not accepted by the pool. A swap has to name a positive quantity of one of the pool's two coins."
  },
  {
    "slug": "sui-book-enew-quantity-must-be-less-than-original",
    "message": "ENewQuantityMustBeLessThanOriginal",
    "chain": "sui",
    "scope": "book",
    "code": 7,
    "meaning": "An order can only be modified downwards. Increasing the size means cancelling and placing a new order, which also gives up its place in the queue."
  },
  {
    "slug": "sui-book-eorder-below-minimum-size",
    "message": "EOrderBelowMinimumSize",
    "chain": "sui",
    "scope": "book",
    "code": 5,
    "meaning": "The order is smaller than the pool's minimum size. Each pool sets its own floor, and an order under it is rejected rather than rounded up."
  },
  {
    "slug": "sui-book-eorder-invalid-lot-size",
    "message": "EOrderInvalidLotSize",
    "chain": "sui",
    "scope": "book",
    "code": 6,
    "meaning": "The order quantity is not a whole number of lots. Every pool has a lot size, and quantities have to be a multiple of it."
  },
  {
    "slug": "sui-constants-ebook-order-mismatch",
    "message": "EBookOrderMismatch",
    "chain": "sui",
    "scope": "constants",
    "code": 1,
    "meaning": "DeepBook stopped on an internal check (a book entry that did not match its order record). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-constants-efill-mismatch",
    "message": "EFillMismatch",
    "chain": "sui",
    "scope": "constants",
    "code": 4,
    "meaning": "DeepBook stopped on an internal check (a fill that did not reconcile against its order). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-constants-eincorrect-mid-price",
    "message": "EIncorrectMidPrice",
    "chain": "sui",
    "scope": "constants",
    "code": 2,
    "meaning": "DeepBook stopped on an internal check (a mid price that failed its consistency check). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-constants-eincorrect-pool-id",
    "message": "EIncorrectPoolId",
    "chain": "sui",
    "scope": "constants",
    "code": 3,
    "meaning": "DeepBook stopped on an internal check (a pool id that did not match the one expected). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-constants-eorder-info-mismatch",
    "message": "EOrderInfoMismatch",
    "chain": "sui",
    "scope": "constants",
    "code": 0,
    "meaning": "DeepBook stopped on an internal check (an order record that did not match its book entry). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-deep-price-eno-data-points",
    "message": "ENoDataPoints",
    "chain": "sui",
    "scope": "deep_price",
    "code": 2,
    "meaning": "There are no DEEP price points recorded for this pool, so a DEEP-denominated fee cannot be priced."
  },
  {
    "slug": "sui-governance-emax-proposals-reached-not-enough-votes",
    "message": "EMaxProposalsReachedNotEnoughVotes",
    "chain": "sui",
    "scope": "governance",
    "code": 4,
    "meaning": "The pool already has the maximum number of proposals this epoch, and this one did not have enough votes to displace one of them."
  },
  {
    "slug": "sui-governance-eproposal-does-not-exist",
    "message": "EProposalDoesNotExist",
    "chain": "sui",
    "scope": "governance",
    "code": 3,
    "meaning": "The proposal voted on does not exist in the current epoch. Proposals do not carry over between epochs."
  },
  {
    "slug": "sui-math-einvalid-precision",
    "message": "EInvalidPrecision",
    "chain": "sui",
    "scope": "math",
    "code": 0,
    "meaning": "DeepBook stopped on an internal check (a precision check in DeepBook's fixed point maths). This is a condition inside DeepBook's own bookkeeping rather than anything wrong with your order, so retrying the same request is unlikely to change the outcome. Nothing was completed and only the gas was spent."
  },
  {
    "slug": "sui-order-einvalid-new-quantity",
    "message": "EInvalidNewQuantity",
    "chain": "sui",
    "scope": "order",
    "code": 0,
    "meaning": "The new quantity for this modification was not valid. An order can only be reduced, and not to zero, which is a cancellation instead."
  },
  {
    "slug": "sui-order-eorder-expired",
    "message": "EOrderExpired",
    "chain": "sui",
    "scope": "order",
    "code": 1,
    "meaning": "The order had already expired by the time this transaction executed, so there was nothing left to act on."
  },
  {
    "slug": "sui-order-info-efokorder-cannot-be-fully-filled",
    "message": "EFOKOrderCannotBeFullyFilled",
    "chain": "sui",
    "scope": "order_info",
    "code": 6,
    "meaning": "This was a fill-or-kill order and there was not enough resting liquidity to fill all of it at your limit price, so none of it was filled. That is the behaviour fill-or-kill asks for: all or nothing."
  },
  {
    "slug": "sui-order-info-einvalid-expire-timestamp",
    "message": "EInvalidExpireTimestamp",
    "chain": "sui",
    "scope": "order_info",
    "code": 3,
    "meaning": "The expiry given for this order is already in the past. An order cannot be placed with an expiry that has passed."
  },
  {
    "slug": "sui-order-info-emarket-order-cannot-be-post-only",
    "message": "EMarketOrderCannotBePostOnly",
    "chain": "sui",
    "scope": "order_info",
    "code": 7,
    "meaning": "The order was sent as both a market order and post-only, which contradict each other. A market order takes liquidity and post-only refuses to."
  },
  {
    "slug": "sui-order-info-eorder-below-minimum-size",
    "message": "EOrderBelowMinimumSize",
    "chain": "sui",
    "scope": "order_info",
    "code": 1,
    "meaning": "The order is smaller than the pool's minimum size. Each pool sets its own floor, and an order under it is rejected rather than rounded up."
  },
  {
    "slug": "sui-order-info-eorder-invalid-lot-size",
    "message": "EOrderInvalidLotSize",
    "chain": "sui",
    "scope": "order_info",
    "code": 2,
    "meaning": "The order quantity is not a whole number of lots. Every pool has a lot size, and quantities have to be a multiple of it."
  },
  {
    "slug": "sui-order-info-eorder-invalid-price",
    "message": "EOrderInvalidPrice",
    "chain": "sui",
    "scope": "order_info",
    "code": 0,
    "meaning": "The order price sits outside the range the pool accepts, or is not a whole number of ticks. Every DeepBook pool has a tick size, and a price between ticks cannot be placed."
  },
  {
    "slug": "sui-order-info-epostorder-crosses-orderbook",
    "message": "EPOSTOrderCrossesOrderbook",
    "chain": "sui",
    "scope": "order_info",
    "code": 5,
    "meaning": "This was a post-only order and it would have matched against an order already resting on the book. Post-only exists to guarantee you add liquidity rather than take it, so instead of filling at a worse price it cancels. The market moved between the price being quoted and the order arriving."
  },
  {
    "slug": "sui-order-info-eself-matching-cancel-taker",
    "message": "ESelfMatchingCancelTaker",
    "chain": "sui",
    "scope": "order_info",
    "code": 8,
    "meaning": "This order would have matched against another of your own orders on the book, and the self-match rule chosen cancelled the incoming side. Nothing was traded with yourself."
  },
  {
    "slug": "sui-pool-eineligible-reference-pool",
    "message": "EIneligibleReferencePool",
    "chain": "sui",
    "scope": "pool",
    "code": 7,
    "meaning": "The pool named as a price reference is not eligible to be one. DeepBook only accepts certain pools as a source of price."
  },
  {
    "slug": "sui-pool-einvalid-deep-price",
    "message": "EInvalidDeepPrice",
    "chain": "sui",
    "scope": "pool",
    "code": 20,
    "meaning": "The DEEP price reference this pool needs was not usable. DeepBook charges fees in DEEP and needs a price for it, and without one the trade cannot be priced."
  },
  {
    "slug": "sui-pool-einvalid-ewmaalpha",
    "message": "EInvalidEWMAAlpha",
    "chain": "sui",
    "scope": "pool",
    "code": 16,
    "meaning": "The smoothing parameter given for the pool's moving average is outside the accepted range."
  },
  {
    "slug": "sui-pool-einvalid-fee",
    "message": "EInvalidFee",
    "chain": "sui",
    "scope": "pool",
    "code": 1,
    "meaning": "The fee supplied for creating this pool was not the amount the registry requires."
  },
  {
    "slug": "sui-pool-einvalid-order-balance-manager",
    "message": "EInvalidOrderBalanceManager",
    "chain": "sui",
    "scope": "pool",
    "code": 8,
    "meaning": "The balance manager presented does not match the one the order was placed with. An order can only be modified or cancelled through the balance manager that created it."
  },
  {
    "slug": "sui-pool-einvalid-quantity-in",
    "message": "EInvalidQuantityIn",
    "chain": "sui",
    "scope": "pool",
    "code": 6,
    "meaning": "The quantity sent into this swap was not accepted. It has to be a positive amount of one of the pool's two coins."
  },
  {
    "slug": "sui-pool-eminimum-quantity-out-not-met",
    "message": "EMinimumQuantityOutNotMet",
    "chain": "sui",
    "scope": "pool",
    "code": 11,
    "meaning": "The swap would have returned less than the minimum you set, so it was rejected rather than filled at a worse rate. That minimum is your slippage protection doing its job. The price moved between the quote and the transaction arriving."
  },
  {
    "slug": "sui-pool-epackage-version-disabled",
    "message": "EPackageVersionDisabled",
    "chain": "sui",
    "scope": "pool",
    "code": 10,
    "meaning": "This transaction went to a version of the DeepBook package that has been turned off. That happens after an upgrade, and it means the app or SDK that built the transaction is pointing at an old address. Updating the app is the fix, and your funds are unaffected."
  },
  {
    "slug": "sui-registry-ecoin-not-whitelisted",
    "message": "ECoinNotWhitelisted",
    "chain": "sui",
    "scope": "registry",
    "code": 7,
    "meaning": "This coin is not whitelisted, so it cannot be used where a whitelisted coin is required."
  },
  {
    "slug": "sui-registry-epackage-version-not-enabled",
    "message": "EPackageVersionNotEnabled",
    "chain": "sui",
    "scope": "registry",
    "code": 3,
    "meaning": "This transaction went to a version of the DeepBook package that is not enabled. That usually means the app or SDK that built it is pointing at an old package address. Your funds are unaffected."
  },
  {
    "slug": "sui-registry-epool-already-exists",
    "message": "EPoolAlreadyExists",
    "chain": "sui",
    "scope": "registry",
    "code": 1,
    "meaning": "A pool for this pair of coins already exists, so a second one cannot be created."
  },
  {
    "slug": "sui-state-ealready-proposed",
    "message": "EAlreadyProposed",
    "chain": "sui",
    "scope": "state",
    "code": 3,
    "meaning": "This balance manager has already made a governance proposal in the current epoch."
  },
  {
    "slug": "sui-state-emax-open-orders",
    "message": "EMaxOpenOrders",
    "chain": "sui",
    "scope": "state",
    "code": 2,
    "meaning": "This balance manager already has the maximum number of open orders on this pool. Cancelling or letting some fill makes room for another."
  },
  {
    "slug": "sui-vault-ehas-owed-balances",
    "message": "EHasOwedBalances",
    "chain": "sui",
    "scope": "vault",
    "code": 8,
    "meaning": "This operation cannot run while the balance manager still owes balances on the pool. Those have to be settled first."
  },
  {
    "slug": "sui-vault-eincorrect-quantity-returned",
    "message": "EIncorrectQuantityReturned",
    "chain": "sui",
    "scope": "vault",
    "code": 6,
    "meaning": "The amount returned to close the flash loan did not cover what was borrowed. A flash loan has to be repaid in full inside the same transaction, so the whole transaction is undone."
  }
]
