/** GENERATED by scripts/build-errmap.ts from scripts/harvested-errors.json. Do not edit by hand. */
export interface SolanaErrorEntry { name: string; reason: string }

export const PROGRAM_ERRMAPS: Record<string, Record<number, SolanaErrorEntry>> = {
  // seen 627x
  "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4": {
    6000: { name: "EmptyRoute", reason: "Empty route." },
    6001: { name: "SlippageToleranceExceeded", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6002: { name: "InvalidCalculation", reason: "Invalid calculation." },
    6003: { name: "MissingPlatformFeeAccount", reason: "Missing platform fee account." },
    6004: { name: "InvalidSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6005: { name: "NotEnoughPercent", reason: "Not enough percent to 100." },
    6006: { name: "InvalidInputIndex", reason: "Token input index is invalid." },
    6007: { name: "InvalidOutputIndex", reason: "Token output index is invalid." },
    6008: { name: "NotEnoughAccountKeys", reason: "Not Enough Account keys." },
    6009: { name: "NonZeroMinimumOutAmountNotSupported", reason: "Non zero minimum out amount not supported." },
    6010: { name: "InvalidRoutePlan", reason: "Invalid route plan." },
    6011: { name: "InvalidReferralAuthority", reason: "Invalid referral authority." },
    6012: { name: "LedgerTokenAccountDoesNotMatch", reason: "Token account doesn't match the ledger." },
    6013: { name: "InvalidTokenLedger", reason: "Invalid token ledger." },
    6014: { name: "IncorrectTokenProgramID", reason: "Token program ID is invalid." },
    6015: { name: "TokenProgramNotProvided", reason: "Token program not provided." },
    6016: { name: "SwapNotSupported", reason: "Swap not supported." },
    6017: { name: "ExactOutAmountNotMatched", reason: "Exact out amount doesn't match." },
    6018: { name: "SourceAndDestinationMintCannotBeTheSame", reason: "Source mint and destination mint cannot the same." },
    6019: { name: "InvalidMint", reason: "Invalid mint." },
    6020: { name: "InvalidProgramAuthority", reason: "Invalid program authority." },
    6021: { name: "InvalidOutputTokenAccount", reason: "Invalid output token account." },
    6022: { name: "InvalidFeeWallet", reason: "Invalid fee wallet." },
    6023: { name: "InvalidAuthority", reason: "Invalid authority." },
    6024: { name: "InsufficientFunds", reason: "Insufficient funds." },
    6025: { name: "InvalidTokenAccount", reason: "Invalid token account." },
    6026: { name: "BondingCurveAlreadyCompleted", reason: "Bonding curve already completed." },
    6027: { name: "IncorrectSwapProgramId", reason: "Swap program ID is invalid." },
  },
  // seen 274x
  "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA": {
    3012: { name: "AccountNotInitialized", reason: "The program expected this account to be already initialized." },
    6000: { name: "FeeBasisPointsExceedsMaximum", reason: "Fee Basis Points Exceeds Maximum." },
    6001: { name: "ZeroBaseAmount", reason: "Zero Base Amount." },
    6002: { name: "ZeroQuoteAmount", reason: "Zero Quote Amount." },
    6003: { name: "TooLittlePoolTokenLiquidity", reason: "Too Little Pool Token Liquidity." },
    6004: { name: "ExceededSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6005: { name: "InvalidAdmin", reason: "Invalid Admin." },
    6006: { name: "UnsupportedBaseMint", reason: "Unsupported Base Mint." },
    6007: { name: "UnsupportedQuoteMint", reason: "Unsupported Quote Mint." },
    6008: { name: "InvalidBaseMint", reason: "Invalid Base Mint." },
    6009: { name: "InvalidQuoteMint", reason: "Invalid Quote Mint." },
    6010: { name: "InvalidLpMint", reason: "Invalid Lp Mint." },
    6011: { name: "AllProtocolFeeRecipientsShouldBeNonZero", reason: "All Protocol Fee Recipients Should Be Non Zero." },
    6012: { name: "UnsortedNotUniqueProtocolFeeRecipients", reason: "Unsorted Not Unique Protocol Fee Recipients." },
    6013: { name: "InvalidProtocolFeeRecipient", reason: "Invalid Protocol Fee Recipient." },
    6014: { name: "InvalidPoolBaseTokenAccount", reason: "Invalid Pool Base Token Account." },
    6015: { name: "InvalidPoolQuoteTokenAccount", reason: "Invalid Pool Quote Token Account." },
    6016: { name: "BuyMoreBaseAmountThanPoolReserves", reason: "Buy More Base Amount Than Pool Reserves." },
    6017: { name: "DisabledCreatePool", reason: "Disabled Create Pool." },
    6018: { name: "DisabledDeposit", reason: "Disabled Deposit." },
    6019: { name: "DisabledWithdraw", reason: "Disabled Withdraw." },
    6020: { name: "DisabledBuy", reason: "Disabled Buy." },
    6021: { name: "DisabledSell", reason: "Disabled Sell." },
    6022: { name: "SameMint", reason: "Same Mint." },
    6023: { name: "Overflow", reason: "Overflow." },
    6024: { name: "Truncation", reason: "Truncation." },
    6025: { name: "DivisionByZero", reason: "Division By Zero." },
    6026: { name: "NewSizeLessThanCurrentSize", reason: "New Size Less Than Current Size." },
    6027: { name: "AccountTypeNotSupported", reason: "Account Type Not Supported." },
    6028: { name: "OnlyCanonicalPumpPoolsCanHaveCoinCreator", reason: "Only Canonical Pump Pools Can Have Coin Creator." },
    6029: { name: "InvalidAdminSetCoinCreatorAuthority", reason: "Invalid Admin Set Coin Creator Authority." },
    6030: { name: "StartTimeInThePast", reason: "Start Time In The Past." },
    6031: { name: "EndTimeInThePast", reason: "End Time In The Past." },
    6032: { name: "EndTimeBeforeStartTime", reason: "End Time Before Start Time." },
    6033: { name: "TimeRangeTooLarge", reason: "Time Range Too Large." },
    6034: { name: "EndTimeBeforeCurrentDay", reason: "End Time Before Current Day." },
    6035: { name: "SupplyUpdateForFinishedRange", reason: "Supply Update For Finished Range." },
    6036: { name: "DayIndexAfterEndIndex", reason: "Day Index After End Index." },
    6037: { name: "DayInActiveRange", reason: "Day In Active Range." },
    6038: { name: "InvalidIncentiveMint", reason: "Invalid Incentive Mint." },
    6039: { name: "BuyNotEnoughQuoteTokensToCoverFees", reason: "buy: Not enough quote tokens to cover for fees." },
    6040: { name: "BuySlippageBelowMinBaseAmountOut", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6041: { name: "MayhemModeDisabled", reason: "Mayhem Mode Disabled." },
    6042: { name: "OnlyPumpPoolsMayhemMode", reason: "Only Pump Pools Mayhem Mode." },
    6043: { name: "MayhemModeInDesiredState", reason: "Mayhem Mode In Desired State." },
    6044: { name: "NotEnoughRemainingAccounts", reason: "Not Enough Remaining Accounts." },
    6045: { name: "InvalidSharingConfigBaseMint", reason: "Invalid Sharing Config Base Mint." },
    6046: { name: "InvalidSharingConfigCoinCreator", reason: "Invalid Sharing Config Coin Creator." },
    6047: { name: "CoinCreatorMigratedToSharingConfig", reason: "coin creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead." },
    6048: { name: "CreatorVaultMigratedToSharingConfig", reason: "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead." },
    6049: { name: "CashbackNotEnabled", reason: "Cashback is disabled." },
    6050: { name: "OnlyPumpPoolsCashback", reason: "Only Pump Pools Cashback." },
    6051: { name: "CashbackNotInDesiredState", reason: "Cashback Not In Desired State." },
    6052: { name: "TokensInVaultLessThanCashbackEarned", reason: "Tokens In Vault Less Than Cashback Earned." },
    6053: { name: "BuybackFeeRecipientNotAuthorized", reason: "Buyback fee recipient not authorized." },
    6054: { name: "AllBuybackFeeRecipientsShouldBeNonZero", reason: "All Buyback Fee Recipients Should Be Non Zero." },
    6055: { name: "NotUniqueBuybackFeeRecipients", reason: "Not Unique Buyback Fee Recipients." },
    6056: { name: "BuybackBasisPointsOutOfRange", reason: "buyback_basis_points must be <= 10_000." },
    6057: { name: "WrongBuybackFeeRecipientsCount", reason: "buyback fee recipients require exactly 8 remaining accounts (or none)." },
    6058: { name: "BuybackFeeRecipientMissing", reason: "Buyback Fee Recipient Missing." },
  },
  // seen 102x
  "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG": {
    6002: { name: "ExceededSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 66x
  "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN": {
    6000: { name: "MathOverflow", reason: "Math operation overflow." },
    6001: { name: "InvalidFee", reason: "Invalid fee setup." },
    6002: { name: "ExceededSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6003: { name: "ExceedMaxFeeBps", reason: "Exceeded max fee bps." },
    6004: { name: "InvalidAdmin", reason: "Invalid admin." },
    6005: { name: "AmountIsZero", reason: "Amount is zero." },
    6006: { name: "TypeCastFailed", reason: "Type cast error." },
    6007: { name: "InvalidActivationType", reason: "Invalid activation type." },
    6008: { name: "InvalidQuoteMint", reason: "Invalid quote mint." },
    6009: { name: "InvalidCollectFeeMode", reason: "Invalid collect fee mode." },
    6010: { name: "InvalidMigrationFeeOption", reason: "Invalid migration fee option." },
    6011: { name: "InvalidInput", reason: "Invalid input." },
    6012: { name: "NotEnoughLiquidity", reason: "Not enough liquidity." },
    6013: { name: "PoolIsCompleted", reason: "Pool is completed." },
    6014: { name: "PoolIsIncompleted", reason: "Pool is incompleted." },
    6015: { name: "InvalidMigrationOption", reason: "Invalid migration option." },
    6016: { name: "InvalidTokenDecimals", reason: "Invalid token decimals." },
    6017: { name: "InvalidTokenType", reason: "Invalid token type." },
    6018: { name: "InvalidFeePercentage", reason: "Invalid fee percentage." },
    6019: { name: "InvalidQuoteThreshold", reason: "Invalid quote threshold." },
    6020: { name: "InvalidTokenSupply", reason: "Invalid token supply." },
    6021: { name: "InvalidCurve", reason: "Invalid curve." },
    6022: { name: "NotPermitToDoThisAction", reason: "Not permit to do this action." },
    6023: { name: "InvalidOwnerAccount", reason: "Invalid owner account." },
    6024: { name: "InvalidConfigAccount", reason: "Invalid config account." },
    6025: { name: "SurplusHasBeenWithdraw", reason: "Surplus has been withdraw." },
    6026: { name: "LeftoverHasBeenWithdraw", reason: "Leftover has been withdraw." },
    6027: { name: "TotalBaseTokenExceedMaxSupply", reason: "Total base token is exceeded max supply." },
    6028: { name: "UnsupportNativeMintToken2022", reason: "Unsupport native mint token 2022." },
    6029: { name: "InsufficientLiquidityForMigration", reason: "Insufficient liquidity for migration." },
    6030: { name: "MissingPoolConfigInRemainingAccount", reason: "Missing pool config in remaining account." },
    6031: { name: "InvalidVestingParameters", reason: "Invalid vesting parameters." },
    6032: { name: "InvalidLeftoverAddress", reason: "Invalid leftover address." },
    6033: { name: "InsufficientLiquidity", reason: "Liquidity in bonding curve is insufficient." },
    6034: { name: "InvalidFeeScheduler", reason: "Invalid fee scheduler." },
    6035: { name: "InvalidCreatorTradingFeePercentage", reason: "Invalid creator trading fee percentage." },
    6036: { name: "InvalidNewCreator", reason: "Invalid new creator." },
    6037: { name: "InvalidTokenAuthorityOption", reason: "Invalid token authority option." },
    6038: { name: "InvalidAccount", reason: "Invalid account for the instruction." },
    6039: { name: "InvalidMigratorFeePercentage", reason: "Invalid migrator fee percentage." },
    6040: { name: "MigrationFeeHasBeenWithdraw", reason: "Migration fee has been withdraw." },
    6041: { name: "InvalidBaseFeeMode", reason: "Invalid base fee mode." },
    6042: { name: "InvalidFeeRateLimiter", reason: "Invalid fee rate limiter." },
    6043: { name: "FailToValidateSingleSwapInstruction", reason: "Fail to validate single swap instruction in rate limiter." },
    6044: { name: "InvalidMigratedPoolFee", reason: "Invalid migrated pool fee params." },
    6045: { name: "UndeterminedError", reason: "Undertermined error." },
    6046: { name: "RateLimiterNotSupported", reason: "Rate limiter not supported." },
    6047: { name: "AmountLeftIsNotZero", reason: "Amount left is not zero." },
    6048: { name: "NextSqrtPriceIsSmallerThanStartSqrtPrice", reason: "Next sqrt price is smaller than start sqrt price." },
    6049: { name: "InvalidMinBaseFee", reason: "Invalid min base fee." },
    6050: { name: "AccountInvariantViolation", reason: "Account invariant violation." },
    6051: { name: "InvalidPoolCreationFee", reason: "Invalid pool creation fee." },
    6052: { name: "PoolCreationFeeHasBeenClaimed", reason: "Pool creation fee has been claimed." },
    6053: { name: "Unauthorized", reason: "Not permit to do this action." },
    6054: { name: "ZeroPoolCreationFee", reason: "Pool creation fee is zero." },
    6055: { name: "InvalidMigrationLockedLiquidity", reason: "Invalid migration locked liquidity." },
    6056: { name: "InvalidFeeMarketCapScheduler", reason: "Invalid fee market cap scheduler." },
    6057: { name: "FirstSwapValidationFailed", reason: "Fail to validate first swap with minimum fee." },
    6058: { name: "IncorrectATA", reason: "Incorrect ATA." },
    6059: { name: "InsufficientPoolLamports", reason: "Pool has insufficient lamports to perform the operation." },
    6060: { name: "InvalidPermission", reason: "Invalid permission." },
    6061: { name: "InvalidWithdrawProtocolFeeZapAccounts", reason: "Invalid withdraw protocol fee zap accounts." },
    6062: { name: "MintRestrictedFromZap", reason: "SOL,USDC protocol fee cannot be withdrawn via zap." },
    6063: { name: "InvalidZapOutParameters", reason: "Invalid zap out parameters." },
    6064: { name: "CpiDisabled", reason: "CPI disabled." },
    6065: { name: "MissingZapOutInstruction", reason: "Missing zap out instruction." },
    6066: { name: "InvalidZapAccounts", reason: "Invalid zap accounts." },
    6067: { name: "InvalidCompoundingParameters", reason: "Invalid compounding parameters." },
  },
  // seen 38x
  "AhGst6Kzenm2DBMvmaCK8pYkh1yjKXtQGLLyrv3SdRTm": {
    6022: { name: "NoQualifyingGroup", reason: "No trigger wallet reached the threshold." },
  },
  // seen 62x
  "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P": {
    3012: { name: "AccountNotInitialized", reason: "The program expected this account to be already initialized." },
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6003: { name: "TooLittleSolReceived", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6023: { name: "NotEnoughTokensToSell", reason: "Not enough tokens to sell." },
    6024: { name: "Overflow", reason: "Overflow." },
    6042: { name: "BuySlippageBelowMinTokensOut", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 29x
  "term9YPb9mzAsABaqN71A4xdbxHmpBNZavpBiQKZzN3": {
    6000: { name: "NonceAlreadyExists", reason: "Nonce already exists." },
    6042: { name: "BuySlippageBelowMinTokensOut", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 22x
  "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ": {
    6003: { name: "StaleReport", reason: "Stale report." },
  },
  // seen 13x
  "proVF4pMXVaYqmy4NjniPh4pqKNfMmsihgd4wdkCX3u": {
    6010: { name: "MinReturnNotReached", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 12x
  "DF1ow4tspfHX9JwWJsAb9epbkA8hmpSEAtxXy1V27QBH": {
    15001: { name: "SlippageLimitExceeded", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    15999: { name: "InvalidInstructionData", reason: "Invalid Instruction Data." },
  },
  // seen 6x
  "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo": {
    6003: { name: "ExceededAmountSlippageTolerance", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 9x
  "6Vo3245eszAb5wuqEMw8mGdbfRUdKbHhDHP5LcaGuTAB": {
    6002: { name: "ZeroSellAmount", reason: "calculated sell amount is zero." },
    6003: { name: "TooLittleSolReceived", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
    6024: { name: "Overflow", reason: "Overflow." },
  },
  // seen 4x
  "T1TANpTeScyeqVzzgNViGDNrkQ6qHz9KrSBS4aNXvGT": {
    6008: { name: "LessThanMinimumAmountOut", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 3x
  "B4cUJzpPVNKdnjnN7x7MhhXzJT5Z9SpteFp3JK3Y7bow": {
    6003: { name: "E3", reason: "E3." },
  },
  // seen 3x
  "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C": {
    6005: { name: "ExceededSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 2x
  "1Rwv1EsfjbrYrZNnfDRrMw8Vp2FK7dXmkxDCYVx5ELS": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 2x
  "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ": {
    6204: { name: "AlreadyCallbackedComputation", reason: "Callback computation already called." },
  },
  // seen 2x
  "Dbx1vaTPYTkWHHvqCaj886avUjzLrRAAes451p3mM3f1": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 2x
  "Hsv7VdZ5ExwCDd5ikxScXqhoJf72hewuh6FJ84m8vFwp": {
    6003: { name: "ExceededAmountSlippageTolerance", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 2x
  "routeUGWgWzqBWFcrCfv8tritsqukccJPu3q5GPP3xS": {
    2022: { name: "ConstraintMintTokenProgram", reason: "A mint token program constraint was violated." },
  },
  // seen 1x
  "31d9yCNLSHbVAkovakovoDJ6DK3jDoaeiNhJZocR1axM": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "3RcTZjM82taLUMEo9KcGWqE165Swm9qb6z2bXPR5m6t1": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "48uujWJNWVKrG733SDAWTYXcASbagQ8kRm9xRHRGR7tq": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "5kwx69srU5eUQ9rz1aNbuPwv44PDVHWKKhtNHY9wVP1f": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "5r7fqrLkrkoRsatEU72ekaNgPqin4NRYpAXsMwmPZiK8": {
    6004: { name: "ExceededSlippage", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "8xPG57qFn4Ujj7PFQYm2xtR1k1oohWvbb8DqyF4K1daa": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "9LYscfq3D9pwkse3bts6BvHzexcZf947uueWSx3UKDqZ": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "B7qnnCiZd6WfNHc4becittNreSCjxqPSrKRtWc1YEZ1R": {
    6002: { name: "NoProfitableRoute", reason: "No Profitable Route." },
  },
  // seen 1x
  "BMek9diydhE7gjeY1kKkiNCfoqF4X7hRMm8WnSDSNZWP": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "BoobsBSMpFRBA91sNwKLYShRRQPH5GjoCH4NhLUt4yRo": {
    6013: { name: "SqrtPriceLimitOverflow", reason: "Square root price limit overflow." },
  },
  // seen 1x
  "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK": {
    6011: { name: "SqrtPriceLimitOverflow", reason: "Square root price limit overflow." },
  },
  // seen 1x
  "CkvEApcoFPWUgBDheYvUzHqtUj58AXop7vwizEieXXSE": {
    3005: { name: "AccountNotEnoughKeys", reason: "Not enough account keys given to the instruction." },
  },
  // seen 1x
  "CoTh2vLV87d3wBM7pgLYkkh4q7WBKcVGnVzL3ABuwVR4": {
    6005: { name: "OutputTooLow", reason: "Final output amount is less than the minimum required amount." },
  },
  // seen 1x
  "DbGxSMpSq3MHRE6WkVFvbfHfUfKUBnewzvsXUTqPwab4": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "DMSFQzhYc6zrd4QM4MxuDVKFmkndzm5442mUHNwo75E9": {
    6002: { name: "TooMuchSolRequired", reason: "The price moved between the quote and the transaction landing, so the trade would have returned less than your slippage setting allows. Nothing was swapped and only the fee was spent. Retry, and raise your slippage tolerance slightly if it keeps happening." },
  },
  // seen 1x
  "GbXAnPpj3cnhfvZimH5KqtDJv7EdBU5xoZPuxwX7dz94": {
    6000: { name: "UnprofitableArbitrage", reason: "The round trip did not increase the balance. Reverting the transaction." },
  },
  // seen 1x
  "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD": {
    6066: { name: "LiquidationRewardTooSmall", reason: "The reward amount is less than the minimum acceptable received liquidity." },
  },
  // seen 1x
  "ord1qJZ3DB52s9NoG8nuoacW85aCyNvECa5kAqcBVBu": {
    3012: { name: "AccountNotInitialized", reason: "The program expected this account to be already initialized." },
  },
  // seen 1x
  "tRunsb6NB127ES14E5Y6pUf3dfJC8DJMPTcbEaWZSLe": {
    6000: { name: "BalanceExceedsThreshold", reason: "Transaction blocked: ATA balance meets or exceeds the threshold." },
  },
  // seen 2x
  "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc": {
    6034: { name: "InvalidSqrtPriceLimitDirection", reason: "Provided SqrtPriceLimit not in the same direction as the swap." },
    6037: { name: "AmountInAboveMaximum", reason: "Amount in above maximum threshold." },
  },
}

export const MAPPED_PROGRAMS = Object.keys(PROGRAM_ERRMAPS)
