import type { TxDiagnosis } from "@txid/blockchain"

/**
 * The presentation layer for a transaction diagnosis.
 *
 * PURE, DETERMINISTIC, NO LLM. `diagnoseTransaction` already produces the
 * structured facts (status, cause, error, fix) from a chain read. This turns
 * those facts into the two things a support agent actually wants and a block
 * explorer never gives: a plain-English HEADLINE, and a copy-paste
 * CUSTOMER MESSAGE they can send without translating anything.
 *
 * Keeping it deterministic is a cost decision as much as a trust one: the free
 * checker runs this on every lookup, and a template table costs nothing per
 * call, where an LLM would scale the bill linearly with traffic. Regulated
 * support teams also will not accept an AI inventing a payment status. Phrasing
 * generated by a model is a later, cached tier for the rare error we have no
 * template for, never the default path.
 */

export type VerdictTone = "success" | "failed" | "pending" | "not_found"

export interface TxVerdict {
  tone: VerdictTone
  /** The big line: what happened, in one plain sentence. */
  headline: string
  /**
   * The sentence an agent pastes into a ticket. No hashes, no gwei, no jargon.
   * Written to be sent to a non-technical customer as-is.
   */
  customerMessage: string
}

/** Category of a mined failure, from the decoded error name. One source, shared. */
function failureKind(error: string | null): string {
  const n = (error ?? "").toLowerCase()
  if (/slippage|priceimpact|minamount|minout|insufficientoutput/.test(n)) return "slippage"
  if (/allowance|approv|notapproved/.test(n)) return "allowance"
  if (/deadline|expired/.test(n)) return "deadline"
  if (/insufficient|balance/.test(n)) return "balance"
  if (/paused|notactive|halted/.test(n)) return "paused"
  return "other"
}

/** Funds never move on a revert, but gas is still spent. Say both, plainly. */
const NO_FUNDS = "No money left your wallet, apart from a small network fee for the attempt."

function failedVerdict(d: TxDiagnosis): TxVerdict {
  const what = d.method ? `Your ${d.method} transaction` : "Your transaction"

  if (d.cause === "out_of_gas") {
    return {
      tone: "failed",
      headline: "This transaction ran out of gas and failed.",
      customerMessage: `${what} didn't go through because it ran out of gas partway. ${NO_FUNDS} Please try again, and if your wallet lets you, raise the gas limit before resubmitting.`,
    }
  }

  if (d.cause === "panic") {
    return {
      tone: "failed",
      headline: "This transaction hit a contract error and failed.",
      customerMessage: `${what} didn't complete because of an error inside the contract it was calling. ${NO_FUNDS} This one is worth reporting to the team so they can look at it.`,
    }
  }

  if (d.cause === "state_dependent") {
    return {
      tone: "failed",
      headline: "This transaction failed because conditions changed while it was being processed.",
      customerMessage: `${what} didn't go through because something changed in the same block it landed in, usually the price moving past the allowed limit or another transaction taking the liquidity first. ${NO_FUNDS} Please try again; if it keeps happening, a little more slippage or a higher fee usually fixes it.`,
    }
  }

  if (d.cause === "custom_error" || d.cause === "revert_reason") {
    const kind = failureKind(d.error)
    switch (kind) {
      case "slippage":
        return {
          tone: "failed",
          headline: "This transaction failed because the price moved too much.",
          customerMessage: `${what} didn't go through because the price moved more than the allowed limit while it was being processed. ${NO_FUNDS} Please try again. If it keeps happening, increasing the slippage tolerance in your wallet settings usually fixes it.`,
        }
      case "allowance":
        return {
          tone: "failed",
          headline: "This transaction failed because the token wasn't approved first.",
          customerMessage: `${what} didn't go through because the token needs to be approved for this action before it can be used. ${NO_FUNDS} Please approve the token when your wallet prompts you, then try again.`,
        }
      case "deadline":
        return {
          tone: "failed",
          headline: "This transaction failed because it expired before completing.",
          customerMessage: `${what} took too long and expired before it could complete. ${NO_FUNDS} Please simply submit it again.`,
        }
      case "balance":
        return {
          tone: "failed",
          headline: "This transaction failed because a required balance was too low.",
          customerMessage: `${what} didn't go through because there wasn't enough of a required token or asset to complete it. ${NO_FUNDS} Please check the balance and try again.`,
        }
      case "paused":
        return {
          tone: "failed",
          headline: "This transaction failed because the contract is paused.",
          customerMessage: `${what} didn't go through because the contract it was using is temporarily paused. ${NO_FUNDS} This is on the protocol's side. Please try again a little later.`,
        }
      default: {
        const named = d.error ? ` (${d.error})` : ""
        return {
          tone: "failed",
          headline: `This transaction was rejected by the contract${d.error ? ` — ${d.error}` : ""}.`,
          customerMessage: `${what} didn't go through: the contract rejected it${named}. ${NO_FUNDS} Please check the requirements for this action and try again.`,
        }
      }
    }
  }

  // unknown_revert or anything else that still reverted.
  return {
    tone: "failed",
    headline: "This transaction failed and was reverted.",
    customerMessage: `${what} didn't complete: it was reverted on-chain. ${NO_FUNDS} Please try again, and if it keeps failing, share this with the team so they can look closer.`,
  }
}

function pendingVerdict(d: TxDiagnosis): TxVerdict {
  const stuck = d.cause === "insufficient_gas_balance"
  return {
    tone: "pending",
    headline: stuck
      ? "This transaction is stuck: there isn't enough to cover the network fee."
      : "This transaction is still pending and hasn't completed yet.",
    customerMessage: stuck
      ? "Your transaction is waiting because there isn't enough of the network's fee token in the wallet to process it. Please add a little of the network token, and it should go through."
      : "Your transaction is still pending on the network and hasn't confirmed yet. In most cases it just needs a little more time and no action is needed. If it's urgent, it can be sped up with a higher fee from your wallet.",
  }
}

/**
 * THE ONE THAT MATTERS MOST for a payments-shaped user: on-chain success while
 * the customer swears no money arrived. The honest, load-bearing answer is that
 * the chain leg is done and the delay is downstream, which turns a day-long
 * escalation into a one-line reply that points at the right party.
 */
function successVerdict(): TxVerdict {
  return {
    tone: "success",
    headline: "This transaction completed successfully on-chain.",
    customerMessage:
      "This transaction went through successfully on the blockchain and the transfer completed as expected. If the money still hasn't shown up, the hold-up is with the service crediting the destination, not the on-chain transfer, so that is where to chase it next.",
  }
}

function notFoundVerdict(): TxVerdict {
  return {
    tone: "not_found",
    headline: "We couldn't find this transaction on any supported network.",
    customerMessage:
      "We couldn't find this transaction on any network we support. The reference may have a typo, or the transaction may never have been broadcast. Please double-check the full transaction ID was copied, and if it was definitely sent, try submitting it again.",
  }
}

export function verdictFor(d: TxDiagnosis): TxVerdict {
  switch (d.status) {
    case "success": return successVerdict()
    case "failed": return failedVerdict(d)
    case "pending": return pendingVerdict(d)
    default: return notFoundVerdict()
  }
}
